### PR TITLE
fix Weblium site builder detection

### PR DESCRIPTION
**Pull request by AlexeyKhristov**
Hi, 

in my previous PR (https://github.com/AliasIO/wappalyzer/pull/3947) I missed with JS detection - this detection is too wide.

Please merge this PR too and sorry about inconvenience

### CODE REVIEW

**Comment by AlexeyKhristov** [comment]
Hi @AliasIO 

Cloud you merge this, please?

**Comment by AliasIO** [comment]
@AlexeyKhristov The pattern seems valid, why is it too wide?

**Comment by AlexeyKhristov** [comment]
Hi @AliasIO 

it was my initial mistake:
We have used `WEBLIUM_DOMAIN` not only in Weblium-built sites, but in other White-label builders, like [draftium.com](draftium.com)
and even in custom built sites. WEBLIUM_DOMAIN is an artifact of our internal libraries.

Please merge this PR - checking WEBLIUM_DOMAIN in js code can cause "false positive" event in non-weblium sites

**Comment by AliasIO** [comment]
Cheers!

**Pull request merged**
