### PR TITLE
FancyBox - Update pattern for script matching

### PR DESCRIPTION
**Pull request by craiglondon**
Updated pattern per 
https://github.com/AliasIO/Wappalyzer/pull/1403#issuecomment-283469838

### CODE REVIEW

**Comment by craiglondon** [comment]
Thanks @gadcam

**Comment by AliasIO** [comment]
Thanks!

**Comment by AlexByte** [comment]
Please set `pack` optional in pattern. Why did you test only on one site?
What about the example from Github `<script src="/path/to/jquery.fancybox.min.js"></script>`?
Your pattern matched random sites from [list](https://trends.builtwith.com/websitelist/Fancybox)
**No** – `<script type='text/javascript' src='https://www.rushlimbaugh.com/wp-content/plugins/otw-portfolio-manager/frontend/js/jquery.fancybox.min.js?ver=4.7.4'></script>`
**No** – `<script src="https://www.teaparty.org/wp-content/themes/teaparty/js/jquery.fancybox.pack.js?x41557"></script>`
**No** – `<script type='text/javascript' src='http://nutritionandhealing.com/wp-content/themes/nmh-revelations/js/jquery.fancybox.js?ver=72fbf5e5b18a676d822586fdb693931b'></script>`
**Yes** – `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.pack.js"></script>`
**No** – `<script type='text/javascript' src='http://nutritionandhealing.com/wp-content/themes/nmh-revelations/js/jquery.fancybox.js?ver=72fbf5e5b18a676d822586fdb693931b'></script>`

You can just search for digits at end, not looking for `v=`.
Its even doesn't worked at the [official site](http://fancyapps.com/fancybox/3/)
`<script src="fancybox/jquery.fancybox.min.js?v=1493403155"></script>`

**Comment by craiglondon** [comment]
@alexbyte.  I could you create a new PR with your proposed changes?  I won't have time to make one any time soon.

**Pull request merged**
