### PR TITLE
Improve fancybox detection

### PR DESCRIPTION
**Pull request by AlexByte**

### CODE REVIEW

**Comment by jvoisin** [comment]
You can use `(?:…)` for your groups ;)

**Comment by AlexByte** [comment]
In my opinion this only complicates the readability.

**Comment by jvoisin** [comment]
But I'll will (a bit) save some memory ;)

**Comment by AliasIO** [comment]
Thanks. I do prefer `(?:)` as it makes it easier to see where the version number is coming from (and it's slightly more optimised).

**Pull request merged**
