### PR TITLE
Update Dynatrace detect and logo

### PR DESCRIPTION
**Pull request by beeme1mr**
The product formerly known as Ruxit is now Dynatrace. This PR removes Ruxit and updates the Dynatrace config to reflect the change.

You can see more information here:
https://www.dynatrace.com/news/blog/dynatrace-ruxit-becomes-dynatrace/

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by nirlya** [comment]
Hi @beeme1mr! 
It seems you have to keep ruxit detection in place. Example : https://billetterie.psg.fr/fr/ is not recognized with Wappanalyzer 6.3.

**Comment by beeme1mr** [comment]
@nirlya, this is correct behavior.  I tested Wappanalyzer 6.3 and https://billetterie.psg.fr/fr/ was correctly detected as using Dynatrace. Please check out the blog post listed above for more info.

Ruxit turned into Dynatrace so you can still see some references to Ruxit. For example, the script is named "ruxitagentjs-*".

**Comment by nirlya** [comment]
My fault! It was my adblock 👍

**Pull request merged**
