### PR TITLE
Adding 'Angular Material' to app.json

### PR DESCRIPTION
**Pull request by ameyanaik11**
[Angular Material](https://material.angularjs.org/) provides a set of reusable, well-tested, and accessible UI components based on Material Design.

_Note: Reusing the 'icon/AngularJS.png' since there is no specific icon for Angular Material._

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@ameyanaik11 No, they do not have their own logo, but they do seem to have pulled the newer one from [Angular 2](https://angular.io). Would you mind adding it in? I found it [here](https://material.angularjs.org/latest/img/icons/angular-logo.svg). You can keep it as an SVG and probably just call it `Angular.svg` (In Angular 1, the developers decided to call it `AngularJS` and in Angular 2, it's just `Angular`).

The regular Angular entry hasn't been updated to check for Angular 2 because there isn't really a good way to do so (see #1030).

**Comment by ameyanaik11** [comment]
@DaAwesomeP Appreciate your comment. I will add the SVG shortly.

**Comment by ameyanaik11** [comment]
@DaAwesomeP, @AliasIO: Done. Kindly review the pull request.

**Comment by AliasIO** [comment]
Thank you.

**Pull request merged**
