### PR TITLE
Add Zeit's now & next.js.

### PR DESCRIPTION
**Pull request by fabe**
Implements the detection of [now](https://zeit.co/now) and [Next.js](https://zeit.co/next).

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by kirainmoe** [comment]
I had a class named ```something__next```, and wappalyzer recognized it as ```Next.js```, but I have never used ```Next.js``` 😂

**Comment by AlexByte** [comment]
@kirainmoe In my cases it was `js-cloud-promo__next` and` b-navigator__next`.

**Comment by fabe** [comment]
Yeah I suspected that it might come to these cases. Will open a PR that fixes this.

**Comment by timneutkens** [comment]
@fabe thanks for implementing this ❤️

**Pull request merged**
