### PR TITLE
Added detection for Medium

### PR DESCRIPTION
**Pull request by Bradman381**
Added the detection of the popular blogging platform Medium. Works on sites that use custom domains with Medium.

### CODE REVIEW

**Comment by craiglondon** [comment]
@Bradman381 Your commit has two different things in it.  Some for Medium, some of Meteor.

**Comment by Bradman381** [comment]
Sorry just fixed it. Forgot to put my other changes on separate branches.

**Comment by craiglondon** [comment]
@Bradman381 no problem.  It's happened to me too

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
