### PR TITLE
Update adnegah advertising network in apps.json

### PR DESCRIPTION
**Pull request by foadabdollahi**

### CODE REVIEW

**Comment by AlexByte** [comment]
Why did you delete `"env": "^ados(?:Results)?$"`?

**Comment by AlexByte** [comment]
You do not know how to load changes from upstream.

**Comment by foadabdollahi** [comment]
i think  ` "env": "^ados(?:Results)?$"` cause not work truely!
in this page https://wappalyzer.com/applications/adnegah in section "Websites using Adnegah" all of site is wrong.
i add http header X-Advertising-By: "adnegah.net" and i want replace this header with ^ados(?:Results)?$

**Comment by AliasIO** [comment]
Duplicate of #1630.

**Pull request closed without merging**
