### PR TITLE
Add AngularDart and Dart to Wappalyzer

### PR DESCRIPTION
**Pull request by 4cm4k1**
This PR does the following:

- Add AngularDart as Web Framework
- Add Dart as Programming Language
- Tweak other Angular entries (Angular, AngularJS, Angular Material) with `excludes` logic

[Angular](https://github.com/angular/angular)'s popularity is already well documented (and included in Wappalyzer), and [AngularDart](https://github.com/dart-lang/angular) is the companion web framework written in [Dart](https://github.com/dart-lang/sdk), a programming language developed by Google.

Here is a [list of websites that use Dart and/or AngularDart](https://www.dartlang.org/community/who-uses-dart).

I successfully ran `./run validate` and manually tested a few websites with the unpacked extension. Please let me know what you think! 😄

### CODE REVIEW

**Comment by jvoisin** [comment]
It's doesn't look [very popular]( https://github.com/dart-lang/angular/stargazers ) :/

**Comment by 4cm4k1** [comment]
Dart (https://github.com/dart-lang/sdk), at least, has ~1,500 stars on GitHub. Both Dart and AngularDart are rapidly growing - especially the Flutter SDK (https://github.com/flutter/flutter).

For clarity, I think it would be important for Wappalyzer to differentiate the flavors of Angular because they are different:

- Angular (TypeScript compiled to JavaScript)
- AngularJS (JavaScript)
- AngularDart (Dart)

**Comment by AliasIO** [comment]
Agree, I'm happy to include these.

The confidence flag can only be used with regular expressions, not with includes and excludes. Mind updating them?

**Comment by gadcam** [comment]
@4cm4k1 You seem to know well these technologies so do not hesitate to review Angular & AngularJS detection :)

**Comment by 4cm4k1** [comment]
Thanks, @AliasIO and @gadcam! I’m going to try to make the adjustments this evening (CST). 🙂

**Comment by AliasIO** [comment]
I'll update these, thank you!

**Comment by 4cm4k1** [comment]
@AliasIO Thank you for doing that! I've been very busy these last few weeks; I started a new dev job. Thanks again!

**Comment by AliasIO** [comment]
No worries, and congrats. :)

**Pull request merged**
