### PR TITLE
Master

### PR DESCRIPTION
**Pull request by phkn**
Updates for Oracle Commerce, Adds Oracle Commerce Cloud

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by phkn** [comment]
No trouble!  I will say I had a little trouble getting the Vagrant test environment running.  So I was not able to end-to-end test this beyond validating the JSON.  Is there another recommended way to test the HTML patterns being used aside from copying simple examples from documentation?

**Comment by AliasIO** [comment]
You can run the [shell scripts](https://github.com/AliasIO/Wappalyzer/tree/master/bin) in any Linux environment, you just need to set the `$WAPPALYZER_ROOT` environment variable. Otherwise TravisCI will run the tests when you submit a pull request:

https://travis-ci.org/AliasIO/Wappalyzer/builds/91711074

**Comment by phkn** [comment]
Got it.  Thanks!

**Comment by q--** [comment]
You will also need [Node.js](https://nodejs.org), run `npm install jsonlint jpm imagemin-cli svgo -g` and `cd` to the `bin` folder and run `npm install`. Then, you can run `wappalyzer-validate` from inside the `bin` folder.

**Comment by AliasIO** [comment]
Yes, basically you'll need to go through the steps in the [Dockerfile](https://github.com/AliasIO/Wappalyzer/blob/master/docker/Dockerfile).

**Comment by DaAwesomeP** [comment]
You can also enable Travis CI on your fork. Just be sure to rebase your commits or use `--amend`.

**Comment by AlexByte** [comment]
@AliasIO Why does an error occur when I run Dockerfile?
> docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./bin/run\": stat ./bin/run: no such file or directory".

**Comment by AliasIO** [comment]
@AlexByte Have a look at the `./run` script. It mounts the repository root as a folder, i.e. the Docker image should be run on the context of the repo.

**Pull request merged**
