### PR TITLE
Enhanced Varbase CMS detection and confidence

### PR DESCRIPTION
**Pull request by moerazem**
- Varbase has two generator tags, therefore meta/generator detection is no longer working. Replaced this with html detection
- Added more HTML detections and confidence score
- Added OSS license flag

### CODE REVIEW

**Comment by nurbek91** [comment]
Greetings , thanks for pr. 
The `html` identifiers  is resource intensive at the current stage. In the near future plan to rewrite all these identifiers  to `dom`
It would be great if you rewrite using this option.

`"dom": "meta[data-preact-helmet='true']",` 

```
 "dom": {
        "iframe[src*='.sekindo.com']": {
          "attributes": {
            "src": ""
          }
        },
        "img[src*='.sekindo.com']": {
          "attributes": {
            "src": ""
          }
        }
      },
```
It would also be great to get a list of sites that are built in virtue of your technology. I could take a look and help with this task if you wish.

**Comment by moerazem** [comment]
For some reason, the `dom` identifier is not working. 
For example I tried `"dom": "meta[name='generator'][content='Varbase']"` in place of `"html": "<meta[^>]+(?:content=\"Varbase\")\\;confidence:99"`. It's not working.

Here are some sites to validate/test on:
- https://www.fitnessfirstme.com/
- https://detroitmi.gov/
- https://www.icarda.org/
- https://www.iaslc.org/

**Comment by moerazem** [comment]
I understand relying on `html` identifiers is resource intensive at the current stage. However, I can see a lot of current detections relying on it.

Can this PR at least get merged for the time being,  while the optimizations to `dom` can be worked on after the merge?

**Comment by nurbek91** [comment]
Hey mate. I see you posted examples. I will look soon and check/fix this points.

**Comment by nurbek91** [comment]
Hey mate try to commit this one :

```
"Varbase": {
      "cats": [
        1
      ],
      "cpe": "cpe:/a:vardot:varbase",
      "description": "Varbase is an enhanced Drupal distribution packed with adaptive functionalities and essential modules.",
      "icon": "varbase.png",
      "implies": "Drupal",
      "dom": "div[class*='varbase-heroslider'],div[class*='varbase-video-player'],div[class*='type-varbase-blog']",
      "js": {
        "drupalSettings.ajaxPageState.libraries": ".+varbase_media.+"
      },
      "oss": true,
      "website": "https://drupal.org/project/varbase"
    }, 


```

**Comment by moerazem** [comment]
Awesome. Thanks for the direction @nurbek91. I'll revise the selectors to make it catch the different cases of Varbase, yet maintain strict detection.
I'll push a new update now.

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
