### PR TITLE
Add Squarespace Commerce/ Ecommerce

### PR DESCRIPTION
**Pull request by nurbek91**
Website:
https://www.squarespace.com/ecommerce-website

Example websites: 
https://www.ageorge.nl/
https://www.12vues.fr/
https://wooterapparel.com
https://www.identitags.com

### CODE REVIEW

**Comment by vfcampo** [comment]
Moving content example from #3513 . A
image

**Comment by vfcampo** [comment]
I can see that the fingerprint in the screenshot are consistent with the other examples
image
image
image
image

**Comment by vfcampo** [comment]
Any idea on how to identify the payment processors on the scan? I can only see them on the checkout page :
image

**Comment by nurbek91** [comment]
image
@vfcampo  I see only available method

**Comment by AliasIO** [comment]
Thanks, I added some additional fingerprints.

The payment method can often only been found on the checkout or cart. In many cases the Lookup API does return these.

**Comment by vfcampo** [comment]
Hey Team, 

Thanks a lot, please let me know when the ecommece is going to be available in the API.




```

{
   "slug":"squarespace",
   "name":"Squarespace",
   "versions":[
   ],
   "trafficRank":0,
   "categories":[
      {
         "id":1,
         "slug":"cms",
         "name":"CMS"
      },
      {
         "id":61,
         "slug":"saas",
         "name":"SaaS"
      }
   ]
}
```

**Comment by AliasIO** [comment]
@vfcampo It's available now. Note that the Lookup API results come from a database so not all websites will be up-to-date with new technologies, this can take a few weeks. You can use the Crawl API to get real-time results.

**Pull request merged**
