### PR TITLE
Adding EC-CUBE,AD EBiS

### PR DESCRIPTION
**Pull request by j059608**
Adding EC-CUBE,AD EBiS

### CODE REVIEW

**Comment by AliasIO** [comment]
Please have a look at the test results, it looks like the PNG image is really an ICO. Would you be able to provide a valid file?

**Comment by j059608** [comment]
I'm sorry.  I was forgot about icons error.
I added valid image. 
Please confirm it.

**Comment by ScionOfBytes** [comment]
@AliasIO Seems legit. Can you merge this?

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
