### PR TITLE
Add HTTP/2 and distinguish it from SPDY

### PR DESCRIPTION
**Pull request by rugk**
Next try of the pinguin-broken PR https://github.com/AliasIO/Wappalyzer/pull/1002

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by rugk** [comment]
So when will a new Wappalyzer version be released? I'd like to use this feature...

**Comment by rugk** [comment]
BTW Have you actually released a version of Wappalyzer with this fix?

**Comment by AliasIO** [comment]
Yep.

**Comment by rugk** [comment]
Nice, I see it is working. I only see a generic icon for it, but well... it looks good anyway.

**Pull request merged**
