### PR TITLE
Squarespace platform update

### PR DESCRIPTION
**Pull request by tomccabe**
This PR updates the Squarespace tracking for accuracy and additional product delineation.

### CODE REVIEW

**Review by rockeynebhwani — COMMENTED** [review]
@tomccabe - We don't add separate entries for each version. You can extract the version and it's shown next to technology. See example in screenshot. If you need a reference on how to extract version, you can check the entry for 'Vue Storefront' in Github OR look at 'Version Syntax' section here - https://www.wappalyzer.com/docs/dev/specification/

image

**Comment by tomccabe** [comment]
> @tomccabe - We don't add separate entries for each version. You can extract the version and it's shown next to technology. See example in screenshot. If you need a reference on how to extract version, you can check the entry for 'Vue Storefront' in Github OR look at 'Version Syntax' section here - https://www.wappalyzer.com/docs/dev/specification/
> 
> image

Thanks @rockeynebhwani, I missed that documentation. Tested locally and good to go!

**Comment by AliasIO** [comment]
Hi Tom, thanks for the PR!

Are the patterns that you removed invalid?

Is `Static.SQUARESPACE_CONTEXT.templateVersion` the same as the Squarespace version? I.e. does it make sense to refer to 'Squarespace 7' if it's a SaaS?

Could you provide a square SVG icon without text that looks good at small sizes?

**Comment by AliasIO** [comment]
Thanks for clarifying/updating!

**Pull request merged**
