### PR TITLE
Improve detection of Froala Editor

### PR DESCRIPTION
**Pull request by stefanneculai**

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by DaAwesomeP** [comment]
This commit is currently causing the build to fail: https://travis-ci.org/AliasIO/Wappalyzer/builds/224815468

**Comment by gadcam** [comment]
Moreover it's not cautious to use the greedy <code>.*</code> that could, maybe, be replaced with a <code>[^"]*</code>.
@stefanneculai  what do you think about using <code>"html": "class=\\"[^\\"]*(?:fr-view|fr-box)"</code> instead ?

**Comment by AliasIO** [comment]
Fixed in 20a41cbeadb4198e9de4d3593d8fe99a1fa8a215.

**Pull request merged**
