### PR TITLE
Add Dream7 CMS

### PR DESCRIPTION
**Pull request by cn42**

### CODE REVIEW

**Comment by kkadosh** [comment]
Hello, you must add the icon in the same PR that which you added the CMS detection.

**Comment by cn42** [comment]
Thanks for your reply, I made a new pull request

**Comment by kkadosh** [comment]
Also can you give some examples please :)

**Comment by cn42** [comment]
I put a website where it is used in the app.json as example

**Comment by kkadosh** [comment]
The "website" field must contains the website of the CMS and not an example. The example must be provide in the PR.

**Comment by AliasIO** [comment]
Closing due to inactivity.

**Pull request closed without merging**
