### PR TITLE
correction data

### PR DESCRIPTION
**Pull request by alfduca**
correction "script": "cdn\\.e-commerceparaguay\\.com", to "url": "cdn\\.e-commerceparaguay\\.com",

### CODE REVIEW

**Comment by AliasIO** [comment]
`url` only works when you're viewing the URL directly, probably not what you have in mind.

**Comment by alfduca** [comment]
sites have to have if or if a link to the url (Example: http://cdn.e-commerceparaguay.com/xxxxxx) is like this? or am I wrong?

**Comment by AliasIO** [comment]
It only matches if that URL is displayed in the URL bar.

**Comment by ScionOfBytes** [comment]
@AliasIO @alfduca Can we consider this issue resolved?

**Pull request closed without merging**
