### PR TITLE
Added razorpay to technologies.json

### PR DESCRIPTION
**Pull request by rohitgulam**
I added Razorpay as a payment processor in technologies.json

### CODE REVIEW

**Comment by rockeynebhwani** [comment]
> I added Razorpay as a payment processor in technologies.json

Thanks... Can you please also add SVG logo in src\drivers\webextension\images\icons. For new technology, we need to add logo so that it shows up in Chrome extension.

**Comment by rohitgulam** [comment]
Okay, I just did that. Added the svg to icons

**Comment by rockeynebhwani** [comment]
> Okay, I just did that. Added the svg to icons

Thanks.. You need to update this in technologies.json also with property "icon". Have a look at other examples in the file.

**Comment by rohitgulam** [comment]
Sure, I'm doing that right now. And also, I haven't add description, should I add that too?

**Comment by rockeynebhwani** [comment]
> Sure, I'm doing that right now. And also, I haven't add description, should I add that too?

Yes.. try to populate as many attributes as you can.

**Comment by rohitgulam** [comment]
How about now? I added icon attribute and description attribute

**Review by rockeynebhwani — APPROVED** [review]
Looks good

**Comment by rockeynebhwani** [comment]
@rohitgulam - Not sure if you picked up on your own OR based on this issue - https://github.com/AliasIO/wappalyzer/issues/4339. Can you please also add check for JS object as mentioned in this issue.

**Comment by AliasIO** [comment]
I'll fix this one up, thanks!

**Comment by rohitgulam** [comment]
> I'll fix this one up, thanks!

Thanks.

**Pull request merged**
