### PR TITLE
Added Ukrainian translation

### PR DESCRIPTION
**Pull request by elsieholmes**

### CODE REVIEW

**Comment by elsieholmes** [comment]
Really? This is the dumbest merge policy I've ever seen on GitHub!
Ignoring earlier PRs that have successfully passed all checks and gladly commenting on newer ones is not hypocritical at all, you know... What a ****s of the developers you are! People like you is one of the reasons I digitally sign my commits and DO NOT allow edits from mainf'ers. 
Just FYI, it's called a really bad practice. Burn in hell with tons of bugs and infinite loops.

**Comment by gadcam** [comment]
If you are pointing at jvoisin or me for example: FYI we are just contributors just exactly as you.
In my case I can not really say that I can speak or even verify an Ukrainian translation so I will not review your PR. And for the maintainer I think it is a lot harder to review a translation that he may not be able to speak than a small piece of code. When I can help AND when I have some time to give to Wappalyzer I will review a PR or answer to an issue.
Moreover, I think that 2 days is not that much for an open-source project like Wappalyzer.

Please remain polite with all the contributors and even with the maintainer.

**Comment by elsieholmes** [comment]
> In my case I can not really say that I can speak or even verify an Ukrainian translation so I will not review your PR. And for the maintainer I think it is a lot harder to review a translation that he may not be able to speak than a small piece of code.

The thing is that the quality of translation is translator's own responsibility, not the repo owner's or maintainers' one, especially, when none of them speaks that language. This kind of stuff usually just gets merged then keeps being maintained by the author of PR.

> Moreover, I think that 2 days is not that much for an open-source project like Wappalyzer.

Agreed, 2 days is not that much, but there is a but. Two days without doing anything and two days with handpicking requests to work with are completely different things and the latter approach is totally f'd up.

I mean I totally get it when the repo owner can't be arsed to get things done (some of my PRs have been waiting for merge for almost a month or so, but all the other PRs in that case had the same problem i.e. it was FAIR ffs), but when I see such an arsehattery, Facepalm is my only reaction.

P.S. I've already translated some projects and it's the first one to give me the problems.

_Sent from my Google Nexus 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AliasIO** [comment]
Lovely, thank you.

**Pull request merged**
