### PR TITLE
Add Mindbody

### PR DESCRIPTION
**Pull request by jordanskole**
```
"Mindbody": {
  "cats": [
    32
  ],
  "html": [
    "<a[^>]+?href=\"https://clients.mindbodyonline.com/classic[^>]\"",
    "<a[^>]+?href=\"http://clients.mindbodyonline.com/[^>]\""
  ],
  "icon":"mindbody.svg",
  "website": "www.mindbodyonline.com"
}
```

### CODE REVIEW

**Comment by jordanskole** [comment]
@ScionOfBytes please review 👍

**Comment by twindual** [comment]
The company appears does appear to offer "Marketing Automation", however there are no test cases (site urls) to test against to verify this. Would you mind providing some first.

**Comment by jordanskole** [comment]
Hey @twindual, 

Happy to. Can you share a bit more about which site urls you are looking for? Examples of companies using Mindbody? Here is one - http://www.natureyoga.com/

Cat `32` Marketing Automation was a "best fit." The company provides membership management, and I guess you could call ecommerce, and online scheduling and appointment management tools.

**Comment by twindual** [comment]
Thanks, that exactly what I was looking for. Your right about "best fit" there really isn't a category that covers all of that.

**Comment by jordanskole** [comment]
bump :bowtie:

**Comment by AliasIO** [comment]
This will identify any website that links to clients.mindbodyonline.com be identified as Mindbody. Can the pattern be made more specific?

**Comment by jordanskole** [comment]
@AliasIO yeah, that was a bit of a concern for me as well, but no - not really. I checked and it seemed like that represented the most common way users were integrating.

**Comment by AliasIO** [comment]
I see. Using an external service to handle bookings doesn't really qualify as a website technology in my opinion. I'm closing this one.

**Pull request closed without merging**
