### PR TITLE
Updated PHP icon (svg)

### PR DESCRIPTION
**Pull request by DmitryKrekota**
I used the image from: https://en.wikipedia.org/wiki/PHP#/media/File:PHP-logo.svg
Permission details: "This work is free and may be used by anyone for any purpose".

### CODE REVIEW

**Comment by AlexByte** [comment]
I believe that this icon will be badly visible on non-retina screens.
image image - on screen 768p

image image - 1080p

**Comment by DmitryKrekota** [comment]
@AlexByte, and now?

**Comment by AliasIO** [comment]
Nice, thanks!

**Comment by AlexByte** [comment]
Icons should be square otherwise they will be converted to png incorrectly.
this icon from bookmarklet

**Pull request merged**
