### PR TITLE
Add PWA Studio / ecommerce , Update GraphQL, Paypal, Klarna Checkout, Adobe Audience Manager

### PR DESCRIPTION
**Pull request by nurbek91**
### website:
https://github.com/magento/pwa-studio
### examples:
on top Magento2
https://www.structube.com/
https://us.elemis.com/
https://www.shoebacca.com/
https://www.goyard.com/

failed  on top Adobe Commerce:
https://www.purolatornow.com/
failed  on top  Magento2:
https://www.jomashop.com/

### CODE REVIEW

**Comment by nurbek91** [comment]
Hey @AliasIO , could you help with a regular expression for such cases.
image
This one helps define the technology but does not pass validation:
`"html": "\\(var\\(--venia-",`
This will probably pass validation, but it does not determine the technology, since it only works for up to the first line:
` "html": "<style>.+\\(var\\(--venia-.+<\\/style>",`

**Comment by AliasIO** [comment]
@nurbek91 You can try using `"css": "--venia-"`.

**Comment by nurbek91** [comment]
Add Adobe Client Data Layer / js framework
Update Algolia,Apple Pay,  GraphQL, Paypal, Klarna Checkout, Adobe Audience Manager

**Comment by nurbek91** [comment]
> @nurbek91 You can try using `"css": "--venia-"`.

For this case, options with html and css attributes did not work during tests.

I was lucky to find specific js objects for this PWA on the demo site https://venia.magento.com/, which are common to all examples and not on simple sites on Magento

**Pull request merged**
