### PR TITLE
Fixes #690

### LINKED ISSUE #690: Livefyre on drive.google.com
Wappalyzer is misdetecting Livefyre on drive.google.com.

### PR DESCRIPTION
**Pull request by noorhammad**
Fixes false positive identifying Livefyre due to generic LF env variable.

### CODE REVIEW

**Comment by q--** [comment]
Odd, I did exactly the same in May 2014 (#544). Did the changes from that pull request get removed somehow?

**Comment by noorhammad** [comment]
@q-- must have at some point.

**Comment by q--** [comment]
Looks like my fix for the Zeuscart pattern got removed as well. No wonder [it isn't being detected](https://wappalyzer.com/applications/zeuscart).

**Comment by AliasIO** [comment]
Thank you.

**Pull request merged**
