### PR TITLE
Update apps.json

### PR DESCRIPTION
**Pull request by glad-tidings**
some website create with pars elecom portal:
http://snaccim.com/
http://snapasteur.com/
http://ostan-kd.ir/
http://ciaofood.ir/
http://baneh.gov.ir/
http://sabz-travel.com/
http://bijar.gov.ir/
http://parselecom.net/
http://www.mariwanuei.com/
http://divandareh.gov.ir/
http://dehgolan.gov.ir/

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! Mind including the icon file too?

**Comment by glad-tidings** [comment]
I am trying to upload icon in src/icons path but get error "Uploads are disabled."
how to send icon?

**Comment by gadcam** [comment]
@glad-tidings You need to upload it on your fork not in this repository directly.

**Comment by glad-tidings** [comment]
tnx **gadcam**
fork and upload icon in src/icons with name "parselecom.png"

**Comment by gadcam** [comment]
Also you need to upload on the good branch so here https://github.com/glad-tidings/Wappalyzer/tree/patch-1/src/icons to be accurate.

**Comment by glad-tidings** [comment]
upload it
https://github.com/glad-tidings/Wappalyzer/blob/patch-1/src/icons/parselecom.png

**Comment by jvoisin** [comment]
I took at look at the website of the [company behind]( https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=parselecom.net&edit-text=&act=url ) `pars elecom portal`:

It has only 109 customers and 71 portals. This does seems to be super few to me. I don't think it's worth including the detection of "pars elecom portal".

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
