### PR TITLE
Added Sqreen.io

### PR DESCRIPTION
**Pull request by sigfriedseldeslachts**
I have added Sqreen.io, which is a protection for applications.
Used by Algolia and some other big companies like docker.

You can check the header on Algolia's login page:
https://www.algolia.com/users/sign_in

Builded and tested in Chrome

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by sigfriedseldeslachts** [comment]
@AliasIO has this been succesfully merged? Sqreen is not present in master branch.

**Comment by AliasIO** [comment]
Looks like it got lost by incorrectly merging a conflict. I'll add it back in.

**Comment by sigfriedseldeslachts** [comment]
Alright thanks

**Pull request merged**
