### PR TITLE
Add support for svg icons in drivers

### PR DESCRIPTION
**Pull request by pallxk**
This adds support for svg icons in following drivers:
* Mozilla Firefox
* Google Chrome
* Bookmarklet
* HTML

Works in address bar and popups.

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@pallxk Great! I see that you added support for the new `icon` attribute.

@AliasIO Could you please drop the SVG for the Wappalyzer logo into the icons folder as `default.svg`? After #1039 I'm going to change all of the no-icon ones with the Wappalyzer icon to that as well as a lot of the popular apps (jQuery, Nginx, Angular, Bootstrap, etc.).

**Comment by AliasIO** [comment]
Thanks!

@DaAwesomeP I don't have the Wappalyzer icon in vector but do have it in a reasonably high res.

**Comment by DaAwesomeP** [comment]
@AliasIO OK, if you could please drop that as `default.png`, that would be great! The [current one](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/default.png) is only 32x32.

**Comment by AliasIO** [comment]
There are more sizes here: https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/firefox/images

**Pull request merged**
