### PR TITLE
Add docker detection

### PR DESCRIPTION
**Pull request by jvoisin**
This can be tested [here](https://www.qwant.com/?q=wappalyzer&t=web)

### CODE REVIEW

**Comment by HazCod** [comment]
I'm having troubles grasping this detection.
What websites do use this? It is not a standard at all.

**Comment by gildasio** [comment]
I was trying to understand about this detection, but testing something (as create a apache instance with and without docker) I can't see this detection working.

**Comment by jvoisin** [comment]
Keep in mind that this is detecting docker by side effect. I will detect __some__ occurrences of docker, but most of them will flight under the radar.

**Comment by AliasIO** [comment]
Is it just this one website that outputs this line?

https://google.com/search?q="This+comment+is+expected+by+the+docker+HEALTHCHECK"

**Pull request merged**
