### PR TITLE
Various updates to work/fit nicely on NPMJS.org

### PR DESCRIPTION
**Pull request by Johanndutoit**
Hi

Did  a few things after be able to install from npmjs.org:

* Was a problem where it was looking for "apps.json" one file up. Tested locally after that first change #43f9b25 and works nicely now
* Updated README format to fit with npmjs.org style
* Created sections
* Updated code sample to include new method
* Updated output code from the code sample update
* Update the package author to @AliasIO 
* Moved Pasindu to contributors
* Added myself as a contributor
* Added contributor section with old info about Wappalyzer and @AliasIO and also myself and Pasindu

Let me know if I missed anything, hope you aren't getting tired of me :). If your happy please publish to npm.

J

### CODE REVIEW

**Comment by Johanndutoit** [comment]
Checkout https://github.com/passmarked/wappalyzer/tree/master/src/drivers/npm for a preview of the readme

**Comment by AliasIO** [comment]
Cheers. I don't think I'll ever grow tired of pull requests.

**Comment by Johanndutoit** [comment]
haha cool, just remember to update the package name on the "install section". Just saw it, once you decide if your going with the current name or going with the new.

**Comment by Johanndutoit** [comment]
Awesome just tested with a sample install, works like a dream. Pleasure working with ya !

**Pull request merged**
