### PR TITLE
Add Farsi (Persian) Language

### PR DESCRIPTION
**Pull request by mrezakootvaal**
Add Farsi (Persian) Language folder and add Farsi Strings to messages.json file.

### CODE REVIEW

**Comment by AliasIO** [comment]
Thank you very much!

**Comment by shangul** [comment]
**It is Persian language not Farsi!!!**
Only in native language we say Farsi!
It is like someone from Germany says, I speak Deutsch! That's stupid, right!?
Please change it also on change log v5.5.5

**Comment by jvoisin** [comment]
Hello,

No need to call us stupid, everybody is acting is good faith to improve Wappalyzer. What exactly do you want us to change? There is not a single occurrence of "Persian" nor "Farsi" in its source code :)

The [Persian]( https://en.wikipedia.org/wiki/Persian_language ) localization is identified as `fa` in Wappalyzer, as specified in [ISO 639-1:2002]( https://en.wikipedia.org/wiki/ISO_639-1 ).

**Comment by shangul** [comment]
> 
> 
> Hello,
> 
> No need to call us stupid, everybody is acting is good faith to improve Wappalyzer. What exactly do you want us to change? There is not a single occurrence of "Persian" nor "Farsi" in its source code :)
> 
> The [Persian](https://en.wikipedia.org/wiki/Persian_language) localization is identified as `fa` in Wappalyzer, as specified in [ISO 639-1:2002](https://en.wikipedia.org/wiki/ISO_639-1).

Well, I didn't call anyone!
I care about Wappalyzer, but this wasn't only about the improvement of Wappalyzer, was also about the name of my country's language.
In my previous comment I mentioned what needs to be changed! an example: [link](https://www.wappalyzer.com/upgraded?v5.5.5)
yes `fa` is the language code of Persian same as `de` for German, I didn't mean the directory root.

**Comment by jvoisin** [comment]
Wappalyzer.com isn't managed via this repository, you might want to send an email directly to @AliasIO because he's the one behind it.

For the record, the changelog is likely autogenerated based on the merged pull-requests :)

**Comment by AliasIO** [comment]
Thanks @shangul, I didn't know that. It's been corrected.

**Comment by mrezakootvaal** [comment]
> 
> 
> Thanks @shangul, I didn't know that. It's been corrected.

@AliasIO Dear Elbert,
[Look at this link in wikipedia](https://en.wikipedia.org/wiki/Persian_language), Persian (/ˈpɜːrʒən, -ʃən/) is the common and international name of the Western Iranian languages within the Indo-Iranian branch of the Indo-European language family and Farsi (فارسی fārsi [fɒːɾˈsiː]) is endonym of it.
So both of them are the same and they'll be use instead of others. 🙂 

According to @jvoisin, 
> The Persian localization is identified as `fa` in Wappalyzer, as specified in [ISO 639-1:2002](https://en.wikipedia.org/wiki/ISO_639-1). 
cause `fa` is the first two letters of the `Farsi ` word.


@shangul You know, I received your disrespect anonymous email 🙂 please read more and more, study well about everything and then speak.

**Comment by shangul** [comment]
> 
> 
> Thanks @shangul, I didn't know that. It's been corrected.

Thank you so much for your action.



> 
> 
> > Thanks @shangul, I didn't know that. It's been corrected.
> 
> @AliasIO Dear Elbert,
> [Look at this link in wikipedia](https://en.wikipedia.org/wiki/Persian_language), Persian (/ˈpɜːrʒən, -ʃən/) is the common and international name of the Western Iranian languages within the Indo-Iranian branch of the Indo-European language family and Farsi (فارسی fārsi [fɒːɾˈsiː]) is endonym of it.
> So both of them are the same and they'll be use instead of others. 🙂
> 
> According to @jvoisin,
> 
> > The Persian localization is identified as `fa` in Wappalyzer, as specified in [ISO 639-1:2002](https://en.wikipedia.org/wiki/ISO_639-1).
> 
> cause `fa` is the first two letters of the `Farsi` word.
> 
> @shangul You know, I received your disrespect anonymous email 🙂 please read more and more, study well about everything and then speak.

I'm well educated in Persian and German universities, and I'm confident with information I'm providing here, the German language was an excellent example to demonstrate the similarity of the foreign and native names of languages.
I already replied to @jvoisin, in German language they use `de` as the language code same as Persians do `fa` for the Persian language! It wasn't the case here!!!
The 639-1 codes are the two first characters of the native language name and the 639-2/B codes are usually the three first characters of the language name in English.
But again, I was talking about the name of the language not the code!!
Wikipedia is not a reliable source.

**Pull request merged**
