### PR TITLE
Improve ActiveCampaign detection

### PR DESCRIPTION
**Pull request by gioamato**
**Changes:**

- Add ActiveCampaign Site Tracking native integration script source URL (*.app-us1.com)
- Add ActiveCampaign Pages scripts source URL (*.ac-page.com)
- Add URL pattern for ActiveCampaign Platform (<account>.activehosted.com)
- Add URL pattern for ActiveCampaign Pages (<account>.ac-page.com)
- Add pricing info ([Price on asking available contacting Sales team](https://www.activecampaign.com/pricing?em=999999&term=yearly&features=1))

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by gioamato** [comment]
Validation failing:
`/ActiveCampaign/url should be string`

Docs saying `url` can be `String | Array`. Should it be just a string?

**Comment by AliasIO** [comment]
The validation is wrong, I'll fix that!

**Comment by gioamato** [comment]
Ok. I'll try to free some time to look at it, if you want.

Also, should I include the protocol regex in `url` values?

**Comment by AliasIO** [comment]
What you did is fine, I've merged the changes. Thank you.

**Pull request merged**
