### PR TITLE
Shopfa Icon

### PR DESCRIPTION
**Pull request by Aghaie**

### CODE REVIEW

**Comment by Aghaie** [comment]
Sample sites Generated by shopfa:
http://azinsanat.com/
http://fabrickala.com/
http://keshtzar.ir/
http://tebesabz.com/
and more in https://shopfa.com/showcases

**Comment by kkadosh** [comment]
You forgot to push the icon file :)

**Comment by Aghaie** [comment]
i cant undrstand what is problem, do i somthing wrong in this pull request?

**Comment by gadcam** [comment]
The CI is not happy because you need to add the icon and the patterns at the same time.

**Comment by Aghaie** [comment]
Okkk, We need to make CI Happy! tnx :D

**Pull request closed without merging**
