### PR TITLE
Add JS field in Wappalyzer.js & for WebExtension driver

### PR DESCRIPTION
**Pull request by gadcam**
First try to add support to match js variable at any depth.
For example with a pattern like this we could detect jQuery version.
```js
"js" : {
    "jQuery.fn.jquery": "(.*)\\;version:\\1"
}
```
It is not working for the moment but here the state of my experiment.
I think the problem could be that we can not send events directly with inject.js as it is not a content script. What do you think @AliasIO ?

### CODE REVIEW

**Comment by AliasIO** [comment]
There is [`content.js`](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/content.js), which should be all you need. You can message it with [`tabs.sendMessage()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/sendMessage).

I think I'd like it better if the pattern wasn't the key in the object, maybe we can do something like this:

```javascript
"js": [
  "jQuery.fn.jquery=(.+)\\;version:\\1"
]
```

This way you don't need to provide an empty string as the value when there is no version to detect.

**Comment by gadcam** [comment]
> There is content.js, which should be all you need. You can message it with tabs.sendMessage().

Thank you I will do it that way.

> I think I'd like it better if the pattern wasn't the key in the object

Then why do we do like this for meta and headers fields. Should we change them all ?

**Comment by jvoisin** [comment]
What about something like:

```json
"js": {
  "jQuery.fn.jquery": "([0-9]+)"
}
```

Or are we going to match on anything else than a version number?

**Comment by gadcam** [comment]
I think we need to keep it as general as possible, and so make no assumption on what we want to match or that it will be a version code / number.

**Comment by jvoisin** [comment]
How about this then:

```json
"js": {
  "jQuery.fn.jquery": "([0-9a-z-]+)\\;version:1"
}
```

I would like to separate the object dereferencing from the matching regexp.

**Comment by gadcam** [comment]
What is the difference with what I offer ?

**Comment by gadcam** [comment]
> Do we want to permit regexps that don't have any matching group by the way? I don't think we should.

Why would be avoid this ? Sometimes knowing a variable is initialized, even if it is not with a text content, can be useful.

**Comment by jvoisin** [comment]
It makes sense.

**Comment by AliasIO** [comment]
@gadcam You're right, let's stick with key/value. We need to be able to handle `true`/`false` values as well so we can set a version number if a property exists, we can probably just omit the regex in thoses cases.

```javascript
"js": {
  "someSoftware.enterprise": "\\;version:Enterprise"
}
```

**Comment by jvoisin** [comment]
Or write something like

```json
"js": {
  "someSoftware.enterprise": ".\\;version:Enterprise"
}
```

**Comment by gadcam** [comment]
I just finished to implement a first working version of the detection by the js field.
You can test it with jQuery and this pattern on StackOverflow for example
```js
"js" : {
	"jQuery.fn.jquery": "(.*)\\;version:\\1"
}
```
You will maybe find this a bit dirty but it is not that easy to pass things from content script to the page context. However I am more than open to better ideas!

**Comment by gadcam** [comment]
I continue to review all the new js patterns.
I removed Jo & Koego as they doesn't exists anymore.
I don't know what to think about Gravity Insights  & LinkSmart.

**Comment by AliasIO** [comment]
Thanks, awesome work. I merged this into master to avoid merge conflicts in every PR.

**Pull request merged**
