### PR TITLE
Auto release submission

### PR DESCRIPTION
**Pull request by louisgv**
## Context 

> I'd like to use this but the way it's set up now I'd have to submit the build to the repository. Do you know how we can get the `webextension.zip` from the latest [release](https://github.com/AliasIO/wappalyzer/releases) instead?

_Originally posted by @AliasIO in https://github.com/AliasIO/wappalyzer/issues/5616#issuecomment-1050472930_

---

This PR fetches the latest release's asset then use that to submit to the stores.

### CODE REVIEW

**Comment by louisgv** [comment]
@AliasIO We can also make it run automatically whenever a new release that's not a draft is created as well, instead of being run manually. Let me know if that's desirable :) 

Also, I was working on the documentation for the libraries behind the `bpp` action, just open sourced them today in case you would like to audit the inner working of the action:

- [Browser Market Submit](https://github.com/plasmo-corp/bms)
- [Mozilla Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/mwu)
- [Chrome Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/cwu)

**Comment by AliasIO** [comment]
Thanks! It says the build step completed successfully but it actually failed to deploy both, apparently because the extension ID is wrong (I don't think it is).

https://github.com/AliasIO/wappalyzer/actions/runs/1913193700

Is there a way to get more error logging?

**Comment by louisgv** [comment]
> Thanks! It says the build step completed successfully but it actually failed to deploy both, apparently because the extension ID is wrong (I don't think it is).
> 
> https://github.com/AliasIO/wappalyzer/actions/runs/1913193700
> 
> Is there a way to get more error logging?

Yes, I will expose a verbose argument and also add more detailed error log to debug the submission process.

For AMO store, there's a bug regarding manifest gecko.id vs Mozilla's uuid (btw it should be the uuid). It throws error if both are specified. I'm looking into it now as well.

Was there a version bump to wappalyzer? Submission always fail if it's resubmitting old version.

**Comment by louisgv** [comment]
@AliasIO moving the convo here into a bpp issue: https://github.com/plasmo-corp/bpp/issues/37

**Comment by AliasIO** [comment]
I tried it again with a new release and ran into the same error:

https://github.com/AliasIO/wappalyzer/runs/5592461615

The extension ID is correct for both and it's a new version number. My keys.json looks like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/v1/keys.schema.json",
  "chrome": {
    "clientId": "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
    "refreshToken": "x//xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "extId": "gppongmhjkpfnbhagpmjfkannfbllamg"
  },
  "firefox": {
    "extId": "wappalyzer@crunchlabz.com",
    "apiKey": "user:xxxxxxx:xxx",
    "apiSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

**Comment by louisgv** [comment]
> I tried it again with a new release and ran into the same error:
> 
> https://github.com/AliasIO/wappalyzer/runs/5592461615
> 
> The extension ID is correct for both and it's a new version number. My keys.json looks like this:
> 
> ```json
> {
>   "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/v1/keys.schema.json",
>   "chrome": {
>     "clientId": "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
>     "refreshToken": "x//xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>     "extId": "gppongmhjkpfnbhagpmjfkannfbllamg"
>   },
>   "firefox": {
>     "extId": "wappalyzer@crunchlabz.com",
>     "apiKey": "user:xxxxxxx:xxx",
>     "apiSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>   }
> }
> ```


For the Firefox extId, can you try using the uuid provided by the AMO store under https://addons.mozilla.org/addon/{ext-name}/edit, in Technical Details. The email uuid only works if it is embedded into the manifest under browser_specific_settingd.gecko.id. Tho, I believe with the jwt based API call, the id need to be the guid.

**Comment by AliasIO** [comment]
The link should be `https://addons.mozilla.org/developers/addon/{ext-name}/edit`. The UUID it shows is the email ID:
Screen Shot 2022-03-18 at 2 22 01 pm
There is also an internal UUID which I don't think worked either:

Screen Shot 2022-03-18 at 2 24 29 pm

The Chrome version returned the same error so maybe it's a different issue?

**Comment by louisgv** [comment]
I think I figured out what's the issue for AMO store. https://github.com/mozilla/sign-addon requires the uuid to be exact as specified, however we have been prepend and appending `{` and `}` without accounting for email based uuid. Fixing this now

**Comment by louisgv** [comment]
new version is up, can be re-run again. @AliasIO I'm thinking, maybe we can separate the Chrome submission from the Firefox submission so that each can be re-run independently. lmk what you think and I will submit another PR fleshing out that idea

**Pull request merged**
