### PR TITLE
Add Social Graphics Library/JavaScript frameworks

### PR DESCRIPTION
**Pull request by JosunLP**
Website:
https://github.com/JosunLP/Social-graphics-library

### CODE REVIEW

**Comment by AliasIO** [comment]
Did you re-indent the file or something? You committed 34,820 changes. :)

**Comment by JosunLP** [comment]
i just used codespaces to save it, that might re-indent the file :/

**Comment by JosunLP** [comment]
should be fine now

**Comment by AliasIO** [comment]
Thank you but this doesn't meet the threshold for inclusion.

https://github.com/AliasIO/wappalyzer/blob/master/CONTRIBUTING.md

> Only widely used technologies are accepted. When creating a pull request, include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

**Pull request closed without merging**
