### PR TITLE
Update anime.js.png

### PR DESCRIPTION
**Pull request by baseplate-admin**
### Website : https://animejs.com

So the icon looks very weird in wappalyzer menu.

Capture

The example logo looks better than the current implementation.

image

So i essentially ripped the image from here and did some image magic :P

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Also on another note @AliasIO can we turn the style in the box to something purple-ish ? The current white box looks kinda weird( to me at least )

**Comment by AliasIO** [comment]
Can you find an SVG version of the icon?

We could maybe use a light purple for the background. Many icons don't look good on a dark background.

**Comment by baseplate-admin** [comment]
> Can you find an SVG version of the icon? 

Sure i will take a look tomorrow.

> We could maybe use a light purple for the background. Many icons don't look good on a dark background.

Enable dark background experimentally. Then slowly remove background from logos that doesn't have transparent background.

**Comment by AliasIO** [comment]
The problem is with dark icons with a transparent background, like WordPress:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/images/icons/WordPress.svg

**Comment by baseplate-admin** [comment]
Maybe we can use this icon for wordpress instead?

**Comment by AliasIO** [comment]
In this case yes but we can't always change a brand's colour. SVG files do support light and dark themes but it will be a lot of work to check and update 3,000+ icons.

**Comment by baseplate-admin** [comment]
> Can you find an SVG version of the icon?

Found it.

> In this case yes but we can't always change a brand's colour. SVG files do support light and dark themes but it will be a lot of work to check and update 3,000+ icons.

I see your point. But in the end ``We could maybe use a light purple for the background.`` looks a good option to me.

**Comment by baseplate-admin** [comment]
@AliasIO  what am i missing? Why is the check failing ?

I just merged your master into mine, so why is it failing?

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
