### PR TITLE
Automatic release builds from tags

### LINKED ISSUE #1513: Tag releases on GitHub
For future releases, it would be nice if the version of the repo could be tagged:
```bash
git commit -m "update manifests to v4.0.1"
git push origin master
git tag v4.0.1
git push --tags origin master
```
This helps to keep track of exactly what happened in what version by bookmarking different points. After a tag, you can go into the releases tab of the repo on GitHub and upload a prebuilt ZIP of the extension for that release. This allows for easier testing of the addon and different versions in different browsers (ex. Opera or the Firefox WebExtension). You can even setup Travis CI to publish the prebuilt binaries whenever a tag is pushed.

### PR DESCRIPTION
**Pull request by DaAwesomeP**
Partially closes #1513

This will:
 - Generate checksums of the build, print them to the Travis console, and save them as a file
 - Publish the builds and checkums whenever a tag is pushed

This requires a GitHub API token generated from [here](https://github.com/settings/tokens) to be encrypted via Travis as described [here](https://docs.travis-ci.com/user/encryption-keys/) and put into line 16 of this commit.

```bash
travis encrypt <GITHUB_API_TOKEN>
# paste the result into line 16 of this commit
```

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
I fixed the merge conflict.

**Comment by AliasIO** [comment]
Awesome, thanks!

**Comment by AliasIO** [comment]
It worked! 👍 

https://github.com/AliasIO/Wappalyzer/releases

**Comment by DaAwesomeP** [comment]
Great!

**Pull request merged**
