### PR TITLE
Add Virgool 

### PR DESCRIPTION
**Pull request by alihaddadkar**

### CODE REVIEW

**Comment by alihaddadkar** [comment]
@jvoisin 
It's publishing platform which can run on any domain. (Like Medium.com etc)

**Comment by jvoisin** [comment]
Can you please show a couple of websites that are hosting it?

**Comment by alihaddadkar** [comment]
@jvoisin 
https://dataio.ir
https://neshan.blog
https://blog.teamcanvas.ir
https://blog.blue-white.co
https://blog.iranfa.ir

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
