### PR TITLE
Add Payplug

### PR DESCRIPTION
**Pull request by fbureau**
Adding PayPlug (European payment gateway) detection into apps.json

### CODE REVIEW

**Comment by AliasIO** [comment]
Looks like you deleted apps.json, probably unintentional. :)

**Comment by fbureau** [comment]
Hello, if I did it, it was completely unintentional  :)

But this is strange because for me the apps.json is still there. Maybe doing a merge before doing my pull request was a bad  idea :(

If you want I can remove it and leave only the payplug detection code ?

**Comment by fbureau** [comment]
Is it better now ? :)

**Comment by AliasIO** [comment]
It looks like you reset to an old version of the master branch, have a look at the changed files:

https://github.com/AliasIO/Wappalyzer/pull/1079/files

**Pull request closed without merging**
