### PR TITLE
Add Chart.js

### PR DESCRIPTION
**Pull request by simonbrunel**
`Chart` seems a pretty common variable name (same for `Chart.js` script filename), please let me know if you think of a better way (than `confidence`) to detect this library.

### CODE REVIEW

**Comment by gadcam** [comment]
First, I think you could add a pattern to detect the CDN version of Chart.js with version detection. (see https://cdnjs.com/libraries/Chart.js)
Then you could find some CSS selectors related to Chart.js, if there are some, or maybe some other global variables specific to Chart.js but I didn't find something obvious.

**Comment by simonbrunel** [comment]
@gadcam thanks for the CDN suggestion. We don't inject CSS right now and I don't think of any other global variables that could help.

**Comment by simonbrunel** [comment]
Thanks @jvoisin. I'm wondering if there is a way to retrieve the version number from a global variable?

**Comment by gadcam** [comment]
Currently, the only way would be to extract it from the name of the global variable.

**Comment by simonbrunel** [comment]
Ok, nevermind, was just looking for a solution for scripts like:

[`https://cdn.jsdelivr.net/npm/chart.js@2/dist/Chart.js`](https://cdn.jsdelivr.net/npm/chart.js@2/dist/Chart.js)

to be more precise. Right now the detected version will be `2` but the CDN serves `2.6.0` (same for [`@latest`](https://cdn.jsdelivr.net/npm/chart.js@2/dist/Chart.js))

**Comment by gadcam** [comment]
I understand what you mean, see #1226 and #277.
We could detect a lot more information with something like that : however is that possible ? What will be the drawbacks of this, especially regarding performance ? If you want to discuss about that you are free to open an issue.

**Comment by simonbrunel** [comment]
I think it's fine for now: I left a comment on #1226, if something moves on that side, we can still submit a new PR with a better version detection.

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
