### PR TITLE
New Category: User Onboarding, New App: UserGuiding

### PR DESCRIPTION
**Pull request by enginaryum**
**New Category:** User Onboarding
Some of the technologies in this field:
https://www.quora.com/What-tools-are-companies-using-to-onboard-new-users

**New App:** UserGuiding
Onboarding software https://userguiding.com

Some of the companies using UserGuiding:
akaunting.com
mobileaction.co
kushfly.com
avansaspro.com
segmentify.com

### CODE REVIEW

**Comment by enginaryum** [comment]
Hey @AliasIO,
Is there anything I am missing?

**Comment by AlexByte** [comment]
https://github.com/AliasIO/Wappalyzer/issues/2307#issuecomment-395599991

**Comment by AlexByte** [comment]
> Only widely used applications should be added. When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

https://www.wappalyzer.com/docs#new-application

**Comment by AlexByte** [comment]
Do you plan to use existing category marketing instead if creating new?

**Comment by enginaryum** [comment]
I recommend adding a category as `User Onboarding In-App Tools`
As you can see on Quora wiki post, there are dozens of tools already operating in this field. And I am quite sure this category will cover at least 10.000 web applications.
If you don't approve the new category, I can go with the existing `Marketing Automation`.

**Comment by AliasIO** [comment]
@enginaryum Thank you! I'm happy to merge this if you include a few others as mentioned in https://github.com/AliasIO/Wappalyzer/issues/2307#issuecomment-390456608.

**Comment by enginaryum** [comment]
@AliasIO 
I've added [Appcues](https://www.appcues.com) and [Pendo](https://www.pendo.io)
I don't know which category they want to be in, so I've added their app only to the new `User Onboarding` category

**Comment by AliasIO** [comment]
That was quick. Thank you.

**Pull request merged**
