### PR TITLE
Add uKnowva to the list

### PR DESCRIPTION
**Pull request by vickyjain05**
Please add uknowva to the list. The logo in PNG format is attached.
uknowva

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks Vicky. It looks like the tests are failing because the PNG is invalid. Are you able to update the file?

**Comment by AliasIO** [comment]
Ah, I just noticed the attachment. I'll fix up the icon.

**Comment by vickyjain05** [comment]
Thanks a Lot Elbert!

I guess the change might take some time to reflect as I cannot see the
listing of uKnowva here

https://wappalyzer.com/applications

Can you tell me approximately how much time this would take ?

thanks

On Sun, Oct 18, 2015 at 6:38 AM, Elbert Alias <notifications@github.com>
wrote:

> Merged #987 <https://github.com/AliasIO/Wappalyzer/pull/987>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AliasIO/Wappalyzer/pull/987#event-438360001>.
>



-- 
Vicky JainConvergence IT Services Pvt Ltd
*Tel*: +91 22 25136632, +91 9967433963
*Email*: vicky@convergenceservices.in
*Website* : www.convergenceservices.in
                   www.uknowva.com
                   www.convergencesupportdesk.com

*Follow us:*
<http://www.facebook.com/pages/Convergence-Services/103055626418452>
<http://twitter.com/#%21/convergencein>
<http://in.linkedin.com/pub/convergence-services/30/b68/968>

CIN: U72900MH2010PTC206642. This email and any files transmitted with it
are confidential and intended solely for the use of the individual or
entity to whom they are addressed. If you have received this email in error
please notify the system manager. This message contains confidential
information and is intended only for the individual named. If you are not
the named addressee you should not disseminate, distribute or copy this
e-mail. Please notify immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system. If you are not
the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.

**Comment by AliasIO** [comment]
I publish a new version every few weeks.

**Comment by vickyjain05** [comment]
Kool.....will wait for the next update :) Please do let me know once it is published!

**Comment by q--** [comment]
The Wappalyzer add-on will let you know when it's been updated, unless you
disabled that in the options menu.
Op 21 okt. 2015 08:23 schreef "Vicky Jain" <notifications@github.com>:

**Comment by vickyjain05** [comment]
Hey Elbert,
Was just wondering why the icon has not reflected yet....let me know if anything is wrong with the files I changed...you can check this site: http://tpf.org.in, it does not show the uKnowva icon yet

**Pull request merged**
