### PR TITLE
Adding Inwemo cryptominer detection

### PR DESCRIPTION
**Pull request by kkadosh**
Since i don't have samples, i can't check if we can detect it via env

### CODE REVIEW

**Comment by gadcam** [comment]
You can add detection via js with this pattern:
```js
"js" : {
  "Inwemo": "",
  "_0x69dd": ""
}
```
A simple sample to find is their own website ;)

**Comment by kkadosh** [comment]
Done , thanks @gadcam :)

**Comment by jvoisin** [comment]
Are you sure that `_0x69dd` isn't a random pattern?

**Comment by AliasIO** [comment]
Thanks!

**Comment by gadcam** [comment]
@jvoisin I can not be sure.. but it is looks like static in https://cdn.inwemo.com/inwemo.min.js

**Comment by gadcam** [comment]
@jvoisin  But this sample of Coin-Have has <code>_0x0e55</code> https://coin-have.com/c/J5jd.js.

**Pull request merged**
