### PR TITLE
Added Woltlab Community Framework

### PR DESCRIPTION
**Pull request by jpbede**

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! Would you be able to get the pull request up-to-date with the latest master and provide a larger icon? SVG would be ideal, otherwise a 64x64 or 32x32 PNG.

**Comment by jpbede** [comment]
Waiting for a bigger logo

**Comment by jpbede** [comment]
done.

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
