### PR TITLE
CloudCart CDN recognition added

### PR DESCRIPTION
**Pull request by pilievwm**
Hello, for some reasons CloudCart app is not recognizable anymore. I`ve added a new way of recognition. All static files are coming from our CND domain cdncloudcart.com
I hope that this change will fix the issue

### CODE REVIEW

**Comment by pilievwm** [comment]
It is strange conflict. It seems that is missing curly bracket at the end.

**Comment by AlexByte** [comment]
This is not a strange conflict, before adding the modifications, you need to update the data of the remote repository and reset the local repository data to match master branch of upstream repository.
```
git fetch upstream
git reset --hard upstream
```
Or for noobs
`git pull upstream`
Modifications are best done in a separate branch.

**Comment by AlexByte** [comment]
Did you test this?
`"script": "^cdncloudcart$",`
Why did you delete it?
`"script": "/cloudcart-(?:assets|storage)/",`

**Comment by AliasIO** [comment]
I fixed a bug that prevented meta tags from being checked, which fixes the CLoudCart issue.

**Comment by pilievwm** [comment]
Guys the problem is that CloudCart app is not recognizable from Wappalyzer and it is not suggested as the main app. Plase check the screen
image

**Comment by AliasIO** [comment]
That's related to #1588.

**Pull request closed without merging**
