### PR TITLE
add zrlog

### PR DESCRIPTION
**Pull request by 94fzb**
ZrLog is a blog program developed in Java. It is simple, easy to use, componentized, and has low memory footprint.

### CODE REVIEW

**Comment by jvoisin** [comment]
The website zrlog.com isn't working here.

**Comment by 94fzb** [comment]
@jvoisin Oh! This webiste have a 301 redirect to https://www.zrlog.com, But I can access it

**Comment by jvoisin** [comment]
It seems that the project [isn't that popular]( https://github.com/94fzb/zrlog ) :/

(also @94fzb is the lead dev)

**Comment by 94fzb** [comment]
Oh, May be poorly supported in English

**Comment by AliasIO** [comment]
Thanks for the PR, this doesn't meet the requirements for inclusion however.

**Pull request closed without merging**
