### PR TITLE
Add Strapi

### PR DESCRIPTION
**Pull request by lauriejim**
# <a href="https://strapi.io"> Strapi</a>

Hello! 

Quick PR to add [Strapi](https://strapi.io) as new app in CMS section.

Thank you for your project!

### CODE REVIEW

**Comment by lauriejim** [comment]
Thank you @jvoisin ! Appreciate to see my PR merged. Did you know when this update will be available on the Store?

**Comment by jvoisin** [comment]
As soon as @AliasIO does his monthly PR-merging. He's the only one with the commit bit :/

**Comment by AliasIO** [comment]
Thanks!

**Comment by lauriejim** [comment]
Thank you @AliasIO !
Waiting for the release 😉

**Pull request merged**
