### PR TITLE
Add Katana Commerce

### PR DESCRIPTION
**Pull request by OzorNox**
Katana Commerce is a powerful new e-commerce platform for B2B and B2C. The English version of our website is coming soon. A dedicated Katana Commerce website is currently in development. 

First examples:
https://www.orchids-and-so.nl
https://www.eijffinger.com
https://www.channeldistribution.nl
https://shop.chrysal.com
https://kaagentwebshop.be
https://www.guitarsupplies.nl

### CODE REVIEW

**Comment by jvoisin** [comment]
Please add ways to detect your application.

**Comment by OzorNox** [comment]
Oke, we are going to include a meta tag in the head: <meta name="powered-by" content="Katana Commerce">

**Comment by jvoisin** [comment]
Do you have an estimation of how many people are using your product? Because I've only found 12 instances of it.

**Comment by OzorNox** [comment]
Our platform is just new so there are not many users yet. But more and more are coming!

**Comment by kkadosh** [comment]
Hi @OzorNox 

I agree with @jvoisin , i don't think that there is enough instance of this technologie used in the world to add it in Wappalyzer. 
Like says in the documentation : 

>When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.
Wappalyzer uses regular expressions to fingerprint web applications.

Since Wappalyzer use regular expression, adding technologies that are not considerably use in the world will slower Wappalyzer for something that will almost never be detected :/

**Comment by OzorNox** [comment]
@jvoisin and @kkadosh : ok fair point, I'll surrender :D

**Pull request closed without merging**
