### PR TITLE
Add Aircall detection

### PR DESCRIPTION
**Pull request by patrocle**
Add Aircall detection

### CODE REVIEW

**Comment by ScionOfBytes** [comment]
@patrocle Hi! Could you provide examples of websites where this can be tested?

**Comment by patrocle** [comment]
Hi ! 
heek.com or aircall.io

**Comment by jvoisin** [comment]
And also [trampolinn.com](https://trampolinn.com/ ).

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
