### PR TITLE
Repair typecho and homeland

### PR DESCRIPTION
**Pull request by istrwei**
Repair typecho and homeland

### CODE REVIEW

**Comment by jvoisin** [comment]
Why the removal of the `.svg` in favor of ` .png` logo?

**Comment by AlexByte** [comment]
Why you haven't updated master a branch with upstream?

**Comment by istrwei** [comment]
Modify the icon, the program icon is icon, not the logo

**Comment by istrwei** [comment]
Very sorry, I have not done a github team operation, so it is wrong, it seems that I have to learn about teamwork git tutorial

**Pull request closed without merging**
