### PR TITLE
add app: infusionsoft

### PR DESCRIPTION
**Pull request by jordanskole**
First time committing an app, so let me know if I did it correctly. If not happy to make edits!

### CODE REVIEW

**Comment by jordanskole** [comment]
```
Error: The pattern uses more capture groups than needed. Use non-capturing groups where appropriate.
Infusionsoft: html: <input (?:[^>]*name="infusionsoft_version" [^>]*value="([^>]*)"|[^>]*value="([^>]*)" [^>]*name="infusionsoft_version") [^>]*/>\;version:\1
```

What is the best way to handle capturing the version number w/o worrying about order?

**Comment by jordanskole** [comment]
@AliasIO just curious, how often do you check in on these? No rush from my end, but I just want to know how to structure my dev process.

**Comment by AliasIO** [comment]
I go through these every few weeks, when I find the time. Your submission looks good, thank you!

**Comment by jordanskole** [comment]
Happy to help!

**Pull request merged**
