### PR TITLE
Add TerriaJS

### PR DESCRIPTION
**Pull request by shuuji3**
This PR adds [TerriaJS]().

**Screenshot**

[Terria Map](https://map.terria.io/)

Screen Shot 2021-08-02 at 22 40 40

I also tested against some of the websites displayed as demo or projects on the website: https://terria.io/

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! Can you add the icon as well please? It's not included in the PR.

**Comment by shuuji3** [comment]
@AliasIO Sorry, I forgot to add it to the commit. I've just included it now.

**Comment by AliasIO** [comment]
Thank you!

**Comment by shuuji3** [comment]
Thank you for merging! 🙂 

Just adding note: The image source is https://github.com/TerriaJS

**Pull request merged**
