### PR TITLE
Fix inconsistent formatting

### PR DESCRIPTION
**Pull request by maxibanki**
Fixes the incorrect formatting to a consistent formatting.

### CODE REVIEW

**Comment by jvoisin** [comment]
Please don't screw up the indentation :/

**Comment by maxibanki** [comment]
I only fixed the incorrect ones afaik, now the indention is consistent.

**Comment by jvoisin** [comment]
It would be nice if you could split this in an other pull-request then ♥

**Comment by maxibanki** [comment]
Is it now okay? #1860 is the new PR for the new app

**Comment by jvoisin** [comment]
Purr-fect ♥

**Comment by AliasIO** [comment]
Thank you. The indentation is fixed automatically at build time.

**Pull request merged**
