### PR TITLE
feat: add KaTeX

### LINKED ISSUE #3566: Add KaTeX
Website: https://katex.org/
Repo: https://github.com/KaTeX/KaTeX

Examples:
-	https://katex.org/
-	https://rqy.moe/Math/homology_algebra_2/
-	https://blog.coelacanthus.moe/tech/welcome-to-fcitx5/

Scripts:
-	`katex.min.js`
-	`katex.min.css`
-	`katex.js`
-	`katex.css`
-	`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css">`
-	`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">`
-	`<script defer="" crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4"></script>`
-   `<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>`

### PR DESCRIPTION
**Pull request by ayalhw**
close #3566 

Website: https://katex.org/
Repo: https://github.com/KaTeX/KaTeX

Comparison with MathJax: https://www.intmath.com/cg5/katex-mathjax-comparison.php (also can be used to test

Some users:
- have a look: https://github.com/KaTeX/KaTeX/network/dependents?package_id=UGFja2FnZS00OTMwMTUxMDA%3D
- their user page: https://katex.org/users.html
- https://hack.chat/
- https://katex.org/
- https://pandao.github.io/editor.md/ (example site of user editor.md)
- https://www.mathwills.com/
- https://fabiocolacio.github.io/Marker/ (example site of user Marker)
- https://spinningnumbers.org/
- https://www.luogu.com.cn/
- https://mcebbs.cn/
- https://sxyugao.top/

and so many sites such as blog (and their theme) use it to display LaTeX (like mathematical formulas and chemical equations and structural formulas) (of course, MathJax is another choice, and its support has been added)
for example:
- https://rqy.moe/Math/homology_algebra_2/
- https://stone-zeng.github.io/2020-05-02-use-opentype-fonts-iii/
- https://www.luogu.com.cn/blog/YouAreDalao/rp-heaps

### CODE REVIEW

**Comment by ayalhw** [comment]
Sorry, I can't understand the error message...

**Comment by ayalhw** [comment]
I remove the image and the line of `icon` key that I added, but there is still same error.
so I guess it's not my wrong...

And can someone help me?

**Comment by KunoiSayami** [comment]
Workflows was fail since 89f08972b8e7f273715659c38381281eebc61660

**Comment by ayalhw** [comment]
@AliasIO the unused image default-safari.svg was added at https://github.com/AliasIO/wappalyzer/commit/d1f425b4b8806c668ae70aa76e9fed027762b361
you should remove or use it

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
