### PR TITLE
Separate Volusion into two technologies (V1 and V2)

### PR DESCRIPTION
**Pull request by adam-dutton**
I figured this would be the best way to add Volusion (V2) into Wappalyzer since it is a completely different platform from the legacy Volusion (V1) platform. Also updated the icon.

### CODE REVIEW

**Comment by jvoisin** [comment]
What do you mean by "completely different platform"? As far as wappalyzer's concerned, it looks like a simple version update from here.

**Comment by adam-dutton** [comment]
> What do you mean by "completely different platform"?

Volusion (V2) started as an independent ecommerce platform with a different name, then we moved to rebrand it to Volusion.

We maintain and support the original Volusion platform (which we call V1), but no longer market it. There are still thousands of V1 websites out there.

There is no current upgrade path from V1 to V2. 

As far as the technology is concerned, they are completely independent platforms.

I did try to come up with a regex to detect V1 or V2 and then set a version based on either, but I'm not very well versed in regex and couldn't tell if it would work as a Wappalyzer pattern.

**Comment by jvoisin** [comment]
Volusion 2 is not written in ASP ?

**Comment by adam-dutton** [comment]
Nope, it's a completely separate product.

**Pull request merged**
