### PR TITLE
Add ipify,ipstack,ipapi, ipapi.co / Geolocation

### PR DESCRIPTION
**Pull request by max-ostapenko**
I think it's time to bring some Geolocation technologies (#4046, #4041)

1. ipify
2. ipstack
3. ipapi
4. ipapi.co
5. ipdata
6. ip-api
7. ipgeolocation
8. IPInfoDB
9. dbip

Selected the ones that are available on >100 websites (based on HTTP Archive dataset)

### CODE REVIEW

**Comment by nurbek91** [comment]
Hi mate, need to fix the descriptions and probably some other things. I'll throw off the full report later .

**Comment by VictorLeP** [comment]
You might consider including `//geoip-js.com/js/apis/geoip2/v2.1/geoip2.js` / `geoip-js.com` from https://dev.maxmind.com/geoip/geolocate-an-ip/client-side-javascript#2-add-a-javascript-snippet-to-your-page (if it meets your popularity threshold)

**Comment by nurbek91** [comment]
@max-ostapenko  Hey mate , updated some parameters and icons a little.
**ipapi.co** website: https://ipapi.co/#pricing
examples: 
https://sportclips.com/
https://www.sleep.org/
https://juicebeauty.com/
https://www.visitrapidcity.com/

```
"ipapi.co": {
      "cats": [
        79
      ],
      "description": "ipapi.co is a web analytics provider with IP address lookup and location API.",
      "icon": "ipapi.co.png", 
      "xhr": "ipapi\\.co/",
      "saas": true,
      "pricing": [
        "freemium",
        "low",
        "payg"
      ],
      "website": "https://ipapi.co"
    },
```
icon:
ipapi co

**ipapi** website: https://ipapi.com/product
exaample: https://obeyclothing.com/

  ```
  "ipapi": {
      "cats": [
        79
      ],
      "description": "ipapi is a real-time geolocation and reverse IP lookup REST API.",
      "icon": "ipapi.png",
      "xhr": "api\\.ipapi\\.com",
      "saas": true,
      "pricing": [
        "freemium",
        "low",
        "payg"
      ],
      "website": "https://ipapi.com"
    },

```
icon:
ipapi

**ipify** website: https://www.ipify.org/
examples: https://www.pens.com/

```
   "ipify": {
      "cats": [
        79
      ],
      "description": "ipify is a service which provide public IP address API, IP geolocation API, VPN and Proxy detection API products.",
      "icon": "ipify.png",
      "xhr": "[api|api64|geo]\\.ipify\\.org",
      "scripts": "\\.ipify\\.org",
      "saas": true,
      "pricing": [
        "freemium",
        "payg",
        "mid",
        "recurring"
      ],
      "website": "https://ipify.org"
    },

```
icon: 
ipify

**ipstack** website: https://ipstack.com/
examples:
https://ergobaby.com/
https://www.akaipro.com/

```
  "ipstack": {
      "cats": [
        79
      ],
      "description": "ipstack is a real-time IP to geolocation API capable of looking at location data and assessing security threats originating from risky IP addresses.",
      "icon": "ipstack.png",
      "xhr": "api\\.ipstack\\.com",
      "js": {
        "window.ENV.ipStackAccessToken": ""
      },
      "saas": true,
      "pricing": [
        "low", 
        "freemium"
      ],
      "website": "https://ipstack.com"
    },
```
icon: 
ipstack

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
