### PR TITLE
Enable multiple headers with the same name & Get scripts via DOM

### PR DESCRIPTION
**Pull request by gadcam**
Solves #1213 & #1107

### CODE REVIEW

**Comment by AliasIO** [comment]
Awesome, thank you.

**Comment by AlexByte** [comment]
@AliasIO Why couldn't you solve this simple problem?

**Comment by AlexByte** [comment]
For each issue it is better to create a separate pull request.

**Comment by gadcam** [comment]
@AlexByte I know and I am sorry, I forgot to branch...

**Comment by AlexByte** [comment]
@gadcam you could use
```
git reset --hard head~4
git checkout -b get-scripts
git cherry-pick af8c7b3..e1cab27
```

**Pull request merged**
