### PR TITLE
Removal of non-used technologies

### PR DESCRIPTION
**Pull request by jvoisin**
As proposed in #1432

### CODE REVIEW

**Comment by AliasIO** [comment]
Squashed it. :)

**Comment by AlexByte** [comment]
@jvoisin I don't think this PR is self-contained. You can use `commit --amend` instead of creating "olol unfuck" and "fix" commits.

**Comment by jvoisin** [comment]
@AlexByte It's ok, it was squashed by @AliasIO :)

**Comment by AlexByte** [comment]
@jvoisin In this case, commits are not completely superfluous

**Pull request merged**
