### PR TITLE
Add detection for Transifex live

### PR DESCRIPTION
**Pull request by rigaspapas**
Detect the [Javascript version](https://www.transifex.com/how-it-works/) of Transifex localization platform.

### CODE REVIEW

**Comment by rigaspapas** [comment]
@gadcam `Transifex.live.lib_version` increases with each new release of the library. How could we take advantage of it?

**Comment by jvoisin** [comment]
Because Wappalyzer can [detect versions]( https://www.wappalyzer.com/docs/specification ) too ;)

**Comment by rigaspapas** [comment]
@jvoisin the clients that use `Transifex-live` always get the latest version of the script using the CDN. It's impossible for a client to use an older version, unless they self-host an older version of the script. Do you think we should include the version anyway?

**Comment by gadcam** [comment]
If it can be self hosted I think we should include version detection : the more information the better!

**Comment by rigaspapas** [comment]
@gadcam I need some help here. Regex `"Transifex.live.lib_version": "(.+)\\;version:\\1"` outputs a `Transifex true` in the pop-up window. Any clue what I am doing wrong?

**Comment by gadcam** [comment]
Your pattern is good, you can add it!
But you found a bug: the feature is quite recent and it looks like we do not manage numbers properly. Thank you!

**Comment by rigaspapas** [comment]
@gadcam I will update the PR to output the version number with the regex I just mentioned. You can merge it once you fix the bug. If you have a better plan, let me know!

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
