### PR TITLE
Added Apisearch - https://apisearch.io

### PR DESCRIPTION
**Pull request by mmoreram**

### CODE REVIEW

**Comment by mmoreram** [comment]
When a script is loaded dynamically, is detected by the engine?

Thanks!

**Comment by nurbek91** [comment]
Hey mate , thanks for PR!!!.

Updated descriptions a bit.
Resized the icon to 32x32.
Updated pricing policy, took information from here https://apisearch.io/prices.html.

There is a small request
Could you please insert a piece of code after the "Apigee" technologies. 
It would also be great to get a list of sites that are built in virtue of your technology, so that I can test and answer your question above, but it seems to work.

```
"Apisearch": {
      "cats": [
        29
      ],
      "description": "Apisearch is a real-time search platform for ecommerce.",
      "icon": "Apisearch.png",
      "scripts": "static\\.apisearch\\.cloud",
      "oss": true,
      "saas": true,
      "pricing": [
        "freemium",
        "low",
        "mid",
        "recurring"
      ],  
      "website": "https://apisearch.io"
    }
```
icon: 
Apisearch

**Comment by mmoreram** [comment]
Hello @nurbek91 

You can check, for example, https://holaprincesa.es
About the changes, great!
PR updated!
Thanks for your review :)

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
