### PR TITLE
Update Persian language + Add MasterkinG framework

### PR DESCRIPTION
**Pull request by masterking32**
Add new update about translate of Persian language.

### CODE REVIEW

**Comment by jvoisin** [comment]
I don't think that "MasterkinG framework" is widely used. Could you please provide some evidences that it is?

**Comment by masterking32** [comment]
Base of this framework is private and +200 site use that.
But I start some new scripts for free release with minimal edition of that framework.
I dont want release list of websites use that for now ...
But I can send you a list of websites, If you send me  a way to contact you private ...
My ID in Telegram, Instagram : masterking32
Thanks.

**Comment by jvoisin** [comment]
Since @AliasIO is selling the lists of websites/technologies, the fact that you don't want to release a list is a bit dull.

Moreover, 200 sites isn't that many, and ten websites is ridiculous.

Also, since Wappalyzer is open-source, having private lists floating around feels super wrong.

**Comment by masterking32** [comment]
Hmm Ok, but I saw some systems in Wappalyzer, The are private project and less than 50 sites usage.
Finally, I have a new idea for Wappalyzer.
You can add a category like "Developers".
That just handle a Header ...
Like: `project-developer: Amin;test.com`
Then all developers can show their website and name to Wappalyzer, without the need to update Wappalyzer.

**Comment by AliasIO** [comment]
I've included the locale changes, thank you. As per @jvoisin I won't be including the framework.

**Pull request closed without merging**
