### PR TITLE
Added Bulma

### PR DESCRIPTION
**Pull request by neoneosa**
I just added Bulma to the detection list. Not all sites will be detected as it uses the normal HTML filter, looking for a bulma(.min).css file. Tested in Opera.

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by ruchern** [comment]
I do not get to see my page being detected as Bulma even with this addition. I am using Webpack and Bulma is being compressed into a generic `app.css` file.

**Comment by gadcam** [comment]
Can you give us an example page to check what is possible to do ?
However I do not have much hope it is ***packed*** and with a ***generic*** name.

**Comment by itsacorn** [comment]
I didnt know what to check for, so i just added a simple file name detection thing. I was gonna do some thing to check if specific classes exist, but some other frameworks might use the same name. I would rather not detect all sites than to get false positives.If someone knows a better way of detecting Bulma, I would appreciate contributions.

**Pull request merged**
