### PR TITLE
added xng.js

### PR DESCRIPTION
**Pull request by ramsondon**
a javascript template loader on top of lodash

### CODE REVIEW

**Comment by AlexByte** [comment]
Disclosure: its the author of the library with 1 star.

**Comment by ramsondon** [comment]
Hi! It would be awesome if xng can be identified by Wappalyzer! :+1:

**Comment by AlexByte** [comment]
Which sites are using this library?

**Comment by ramsondon** [comment]
unfortunately I think no site except my github page but the project is brand new... so I can not expect anybody to use it right now...

**Comment by AlexByte** [comment]
So adding is useless

**Comment by ramsondon** [comment]
no problem... it's your decision.. it's your project.. I'll try to push it and then I'll be back :) !! best, Matthias

**Comment by AlexByte** [comment]
LOL, it's not my project.

**Comment by AliasIO** [comment]
Thanks for the PR @ramsondon. I have to agree with @AlexByte though.

**Pull request closed without merging**
