### PR TITLE
Improve a bit prestashop detection

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by ScionOfBytes** [comment]
@jvoisin Could you provide examples of where these rules hold?

**Comment by jvoisin** [comment]
Sure:

- [here]( moviseg.com ) for the first regexp. Just ask your search engine about "Powered by Prestashop", you'll see a lot of people asking how to remove it ;) 
- [here]( https://www.btwin.com/en/home ) for the second one. This is a signature of Prestashop modules blocks ;)

**Comment by ScionOfBytes** [comment]
Awesome. Looks good to me.

**Comment by jvoisin** [comment]
And also [here]( https://www.moondreamwebstore.fi).

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
