### PR TITLE
Include Bludit CMS

### PR DESCRIPTION
**Pull request by dignajar**
Hi,
I would like to include Bludit CMS.

Here a demo with the header to detect the CMS.
https://demo.bludit.com

Regards

### CODE REVIEW

**Comment by jvoisin** [comment]
[Only 400 stars]( https://github.com/bludit/bludit )

**Comment by dignajar** [comment]
> [Only 400 stars](https://github.com/bludit/bludit)

There is some rule about the stars in GitHub ?

**Comment by jvoisin** [comment]
There is [one about popularity]( https://www.wappalyzer.com/docs ), yes:

> Only widely used applications should be added. When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

**Comment by dignajar** [comment]
ok, feel free to close the PR.

**Comment by AliasIO** [comment]
Closing. Thank you!

**Pull request closed without merging**
