### PR TITLE
Changes to include overlays

### PR DESCRIPTION
**Pull request by mgifford**
These companies make claims, but do not achieve WCAG compliance or produce accessible sites.

### CODE REVIEW

**Comment by rockeynebhwani** [comment]
@mgifford - You can see all such tech/overlays being tracked here - https://www.wappalyzer.com/technologies/accessibility/. Have you updated description for all these? Can you please check?

**Comment by mgifford** [comment]
@rockeynebhwani I looked at all 14 technologies in the accessibility category. The corrections I am making did not apply to the ones I didn't edit. TextHelp, UsableNet, eSSENTIAL Accessibility & Nagich all seem accurate from the descriptions. They are claiming to be no more or less than the existing description. 

Thanks for asking about that though.

**Review by rockeynebhwani — APPROVED** [review]
Changes look good to me.

**Comment by AliasIO** [comment]
Thanks!

**Comment by thibaudcolas** [comment]
For people interested in this – I have proposed reverting this change for eSSENTIAL Accessibility in #6755. As far as I can tell they don’t provide an overlay.

**Comment by mgifford** [comment]
Makes sense to me. Several of their team signed the document on https://overlayfactsheet.com so...

**Pull request merged**
