### PR TITLE
add Dash as PHP framework with internal CMS as addons

### PR DESCRIPTION
**Pull request by evazzadeh**

### CODE REVIEW

**Comment by jvoisin** [comment]
Yet another php framework with no user (1 star on github), written by the author of this pull-request.

**Comment by evazzadeh** [comment]
Wappalyzer need star!?
This PHP framework used by Iranian developer and many of them is not active on Github!

**Comment by jvoisin** [comment]
I don't know much about the Iranian web, but it seems useful to me to know that you're the author of this framework, and that no one on github is using it.

**Comment by evazzadeh** [comment]
@jvoisin 
PHP frameworks is created to used in PHP websites; not for star it in Github! 

Dash is new version of our old framework, [Saloos](https://github.com/ermile/saloos). check it.

**Comment by AliasIO** [comment]
I'm with @jvoisin on this one. Please feel free to join the eligibility discussion in #1742.

**Pull request closed without merging**
