### PR TITLE
Angular version detection

### PR DESCRIPTION
**Pull request by gadcam**
Solves #1434.

### CODE REVIEW

**Comment by gadcam** [comment]
@AlexByte Are you sure we need to consider them as different ? Because in https://angularjs.org/ we can read :
>This site and all of its contents are referring to AngularJS (version 1.x), if you are looking for the latest Angular, please visit angular.io.

**Comment by AlexByte** [comment]
I am sure.
> Angular is a complete rewrite from the same team that built AngularJS.

**Comment by gadcam** [comment]
@AlexByte fixed in 27d4552.

**Comment by AliasIO** [comment]
Merged manually, thanks!

**Comment by AlexByte** [comment]
I meant that there should be two JS frameworks in apps.json: AngularJS and Angular.

**Comment by gadcam** [comment]
So the html pattern should point to Angular and the other patterns to AngularJS ?

**Comment by gadcam** [comment]
So the html pattern should point to Angular and the other patterns to AngularJS ?

**Comment by AlexByte** [comment]
Yes

**Pull request closed without merging**
