### PR TITLE
Adding slim.js

### PR DESCRIPTION
**Pull request by eavichay**

### CODE REVIEW

**Comment by jvoisin** [comment]
With only [475 stars]( https://github.com/eavichay/slim.js ), the project doesn't look very popular/used :/

**Comment by eavichay** [comment]
@jvoisin Obviously, I would like to showcase the library. Is that a problem?

**Comment by gadcam** [comment]
@eavichay  See https://www.wappalyzer.com/docs
>Adding a new application
>....
>Only widely used applications should be added. When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

**Comment by AliasIO** [comment]
Cool project but we have to be a little strict with the applications we include unfortunately.

**Pull request closed without merging**
