### PR TITLE
Add Ant Design detection

### PR DESCRIPTION
**Pull request by yesmeck**
[Ant Design](https://github.com/ant-design/ant-design) is a popular React component library with [many users](https://github.com/ant-design/ant-design/issues/477).

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by yesmeck** [comment]
Hello @AliasIO , I found that Ant Design was removed in the master branch, do you know why?

**Comment by yesmeck** [comment]
Seems it was removed in this commit https://github.com/AliasIO/Wappalyzer/commit/7776623fb77e7b25874695201cefddb5c0fce3f6 accidentally.

**Comment by AliasIO** [comment]
Added it back in, sorry about that.

**Comment by yesmeck** [comment]
Thanks @AliasIO

**Comment by afc163** [comment]
Cannot detect https://app.mfy.im/login

**Comment by yesmeck** [comment]
Screen Shot 2019-04-10 at 19 05 04

**Comment by afc163** [comment]
image

💔 Firefox don't works.

**Pull request merged**
