### PR TITLE
Add a way to detect Gazelle

### LINKED ISSUE #2047: backend -Gazelle?
add support in Gazelle sites and it's Dependencies
https://github.com/WhatCD/Gazelle
memcache and sphinx

Memcached
Sphinx
procps-ng
Git
GCC/G++
Boost
and more

### PR DESCRIPTION
**Pull request by jvoisin**
This can be tested [here](http://159.89.252.33/torrents.php) and [here](https://empornium.sx)

This should close #2047

### CODE REVIEW

**Comment by gadcam** [comment]
You can also add GazURL as a js pattern ;)

**Comment by jvoisin** [comment]
Travis is red for reasons unrelated to this PR :/

**Comment by xrTor** [comment]
gazelle isnt a search engine, its a web framework based on php

**Comment by jvoisin** [comment]
Its repository says:

> Gazelle is a web framework geared towards private BitTorrent trackers.

It looks more like a search engine for torrents than a framework in the classical sense of it.

**Pull request merged**
