### PR TITLE
Updated Thelia specification

### PR DESCRIPTION
**Pull request by bibich**
Updated Thelia specification

### CODE REVIEW

**Comment by q--** [comment]
Are you sure the Theila version matching the patterns you removed is in use _nowhere_?

**Comment by bibich** [comment]
In fact, the version can't be detected, so the removed pattern was useless.

**Comment by bibich** [comment]
Is there something wrong with this PR, an update to do ?

**Comment by AliasIO** [comment]
No, I've just been slack with merging. Thank you. :)

**Comment by bibich** [comment]
No problems :)
Thanks.

**Comment by gadcam** [comment]
It's a good thing that you updated the patterns but I don't understand why did you remove the former patterns ? (They both match on http://demo.thelia.net/.)

**Comment by bibich** [comment]
Yes it matches on http://demo.thelia.net/ because this site uses our default template (theme).
But in most cases, Thelia websites don't use this template or remove the mata tag generator.
 
And for the second pattern (the Set-Cookie), it could be deactivated, or it happens only on rare occasions.

**Comment by gadcam** [comment]
Ok , I didn't know that but it's same for any pattern: if someone wants to hide all the tools powering a website from Wappalyzer he can.
In my opinion the better would be to keep all the patterns: it costs us almost nothing and it would improve the detection rate.

**Pull request merged**
