### PR TITLE
Add SVG support to apps.json, building, and validating

### PR DESCRIPTION
**Pull request by DaAwesomeP**
- Updated schema to make the new `icon` attribute valid
 - Updated all apps in `apps.json` to have the new `icon` attibute
 - Updated icon validation to validate for both SVGs and PNGs
 - Updated build script to compress SVGs
 - Updated NodeJS build dependencies
 - Updated Travis build script to new LTS version of NodeJS (4.2.1)
 - Updated Travis build script to show file sizes in kB at end of build
 - Updated Travis to newer, faster infrastructure (`curl` and `zip` are already installed and `sudo` isn't needed in Travis): http://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
This will close #1004.

**Comment by DaAwesomeP** [comment]
Not sure what it thinks the deletions are in `apps.json`. Maybe I messed up the spacing or newlines. It seems to be fine though.

**Comment by DaAwesomeP** [comment]
I have ***not*** updated the wiki about the new `icon` attribute.

**Comment by AliasIO** [comment]
Awesome, thanks. We'll still need to update the drivers to actually work with this.

**Comment by gadcam** [comment]
Well done! Don't you think that we should keep a default dehaviour ? (i.e. no field icon when the icon name is appName.png)

**Comment by DaAwesomeP** [comment]
@gadcam that's what [I thought that we should do](https://github.com/AliasIO/Wappalyzer/issues/1004#issuecomment-150998545) to avoid the need to add a field to every single app.

**Comment by gadcam** [comment]
@DaAwesomeP Sorry I did not see the comments on issue #1004, then it's perfect!

**Pull request merged**
