### PR TITLE
Add additional pattern to detect jQuery UI

### PR DESCRIPTION
**Pull request by craiglondon**
Test at 
http://www.khet.com/

### CODE REVIEW

**Comment by jvoisin** [comment]
Won't this one trigger some false positives?

**Comment by craiglondon** [comment]
Maybe?   How do suggest the pattern be improved to avoid that?

**Comment by jvoisin** [comment]
I don't know, this is why I was asking :D

**Comment by craiglondon** [comment]
I guess I'll close this request until I can find more examples

**Pull request closed without merging**
