### PR TITLE
Remove some useless app

### PR DESCRIPTION
**Pull request by jvoisin**
All of them have zero detection on wappalyzer.com

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by AlexByte** [comment]
You mustn't delete technologies.

**Comment by gadcam** [comment]
@AlexByte I do not get your point : these app were never detected.
He just removed patterns that were not working. I do not see any "editorial" choice behind it.

**Comment by AlexByte** [comment]
@gadcam Actually, there is a [threshold](https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-292682691)for data to be displayed on the website.

**Comment by gadcam** [comment]
@AlexByte You are right
> The applications needs to be detected on at least 100 websites to be displayed.

So my comment will be a bit more nuanced.
According to the Chrome Web Store there are 733 556 active installations & 76 477 for Addons Mozilla.
I think if almost 800000 users does not find more than 100 website using a technology either the pattern is bad or there are very few website using a same piece of code and so that is irrelevant to integrate it...

As the documentation states
>Only widely used applications should be added. When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base. 

So according to the current policy of the project this PR seems 100% ok to me. If you are not happy with that I think the best way to proceed is to open a separate issue to exchange on this topic :)

**Comment by AlexByte** [comment]
@gadcam In the list there are technologies with 1 or 10 sites.
>The applications needs to be detected on at least 100 websites to be displayed.
I think this is written about displaying URLs of sites.
98 detections https://www.wappalyzer.com/technologies/cotonti - no URLs
100 detections https://www.wappalyzer.com/technologies/amaya - there is URLs

**Comment by AlexByte** [comment]
@gadcam What is the project policy? Criteria for technologies removal are not defined. This [issue] (https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-287801535) is not closed.

**Comment by pvanschy** [comment]
I agree with @AlexByte that 1c-Bitrix should not be removed. This is a very popular Ecommerce Platform in Russia, and identifying this is useful for some users. There may be an issue with the code.

**Comment by AlexByte** [comment]
@pvanschy detection worked correctly. Perhaps the reason was in [this](https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-395528191) and because not many Wappalyzer users encounter 1c-bitrix.

**Pull request merged**
