### PR TITLE
adding shapecss

### PR DESCRIPTION
**Pull request by MicroDreamIT**
adding shapecss, for detail, please check https://shapecss.com

### CODE REVIEW

**Comment by MicroDreamIT** [comment]
continuous-integration/travis-ci/pr — The Travis CI build failed

I dont understand it. It seems to be too hard.

**Comment by gadcam** [comment]
See line 904 of the TravisCI log :
<code>Error: Missing file for app "Shapecss": src/icons/Shapecss.svg</code>
You need to add an icon see [Adding a new application](https://github.com/AliasIO/Wappalyzer/wiki/Contributing#adding-a-new-application)

**Comment by MicroDreamIT** [comment]
Sir, take a look its worked, https://github.com/AliasIO/Wappalyzer/pull/1565

**Comment by gadcam** [comment]
My bad, I didn't see the other pull request. These 2 pull together are making a whole that is okay for TravisCI, however the classic process is to submit both in the same request.
#1565 shouldn't have passed the tests imo, what do you think @AliasIO ? Shouldn't we check that each icon is used at least one time ?

**Comment by MicroDreamIT** [comment]
Sir, What am i suppose to do then? do I have to commit again? Is everything ok from my end? If not so can you do me favor to make it works for me? I am confusing. I am failing in every kind of test . :(

**Comment by AliasIO** [comment]
Thanks @MicroDreamIT.

@gadcam Yep, good idea.

**Comment by MicroDreamIT** [comment]
Thank you. When it will be working?

@AliasIO @gadcam :)

**Comment by AlexByte** [comment]
@AliasIO Why add 4-star technology to Github? And then create an issue with a proposal to remove unused technologies?

**Pull request merged**
