### PR TITLE
Escaped a bunch of \'s

### PR DESCRIPTION
**Pull request by brandonkelly**
If these `\`s aren’t escaped property, they will be discarded when the JSON is decoded.

### CODE REVIEW

**Comment by AliasIO** [comment]
Right you are. Thank you!

**Comment by brandonkelly** [comment]
@AliasIO looks like a lot of this was undone in 0fbaa9622c0b45efe80630196e07f65c82ff80c9 - was that intentional?

**Comment by AliasIO** [comment]
Not intentional, not sure what happened there. Fixed in fd9c20c700f10796a7aaf429095991c19b25d51c.

**Comment by brandonkelly** [comment]
@AliasIO This was undone again in 0a63ef2ddd3efbf2fee4d3cf6f980792f065dd57. Maybe something is messed up with a build script?

**Comment by AliasIO** [comment]
@brandonkelly Good point, it might be the JSON linter.

**Comment by brandonkelly** [comment]
Will it be fixed soon? Whenever this happens, any app regexes that have `\b` become undetectable by Wappalyzer, as it ends up searching for a litera `b` rather than applying a `\b` (boundary) to the regex. So for example instead of looking for `Craft CMS` with boundaries on each end, it’s looking for `bCraft CMSb`.

**Comment by brandonkelly** [comment]
Thanks!

**Pull request merged**
