### PR TITLE
Improve Gunicorn

### PR DESCRIPTION
**Pull request by baseplate-admin**
Gunicorn Implies Python

### CODE REVIEW

**Comment by AliasIO** [comment]
Does Gunicorn exclusively work with Python applications or is Gunicorn itself written in Python?

**Comment by baseplate-admin** [comment]
Gunicorn is written in python. And it only works with python wsgi applications. 

https://github.com/benoitc/gunicorn

**Comment by AliasIO** [comment]
In the case of web servers, Python should only be implied if it serves an application written in Python. We use to imply Java for TomCat but it's confusing as it might be serving an application written in PHP. So unless the servers exclusively work with Python applications, the implies should be removed.

**Comment by baseplate-admin** [comment]
But Gunicorn works exclusively with python.

**Comment by AliasIO** [comment]
Ok great. :) What about the others you submitted?

**Comment by baseplate-admin** [comment]
Bout others. Yea they are written in python. I hyperlinked Their Github page. You can take a look for yourself

**Comment by AliasIO** [comment]
I mean, do they exclusively serve applications written in Python?

**Comment by baseplate-admin** [comment]
Yep.

**Pull request merged**
