### PR TITLE
Add Category For WordPress Hosting & Update Exisiting Entries

### PR DESCRIPTION
**Pull request by noodles**
As detailed in this FR:

Add Category For WordPress Hosting #4303

### CODE REVIEW

**Comment by noodles** [comment]
Does it make sense to switch these WP hosting entries to use `requires` instead of `implies`

**Comment by AliasIO** [comment]
That depends. Should this perhaps be a generic 'hosting' category?

**Comment by noodles** [comment]
The ones listed in #4303 are all WordPress only hosting so it's big enough to be a standalone category BUT thinking about how it would appear in the plugin, just "hosting" might make more sense.

**Comment by noodles** [comment]
Would just `hosting` be OK for the category name?

    "88": {
      "name": "Hosting",
      "priority": 9
    }

**Comment by AliasIO** [comment]
Yes, let's go with that. That way we can add other web hosts as well.

**Pull request merged**
