### PR TITLE
Add SkyVerge / Payment proc

### PR DESCRIPTION
**Pull request by nurbek91**
#3621 
Website:
https://www.skyverge.com/

Example website:
https://www.pintailcoffee.com/

### CODE REVIEW

**Comment by vfcampo** [comment]
Hey Team , happy new year
I can see that this website is still not showing up skyverge
image
Can you take a look?

**Comment by vfcampo** [comment]
I assumed it will showup after the month charged but that was not the case

**Comment by nurbek91** [comment]
Hey @vfcampo  mate .  
image
I checked this site specifically. locally the technology is determined. Apparently the update has not yet reached the chrome extension. But this is not in my competence. Just guesswork

**Comment by AliasIO** [comment]
It's in today's update!

**Pull request merged**
