### PR TITLE
Added Sulu CMS

### PR DESCRIPTION
**Pull request by chirimoya**
Official Website: http://sulu.io/en

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks!

**Comment by wachterjohannes** [comment]
I have additional questions about this PR. When will this be released? Or is it already?

We have encountered that we response the `x-generator` in 2 different ways on with uppercase X and G and one all lowercase. Make this any problems? /cc @chirimoya

**Comment by AliasIO** [comment]
I just published a new version of the extensions.

**Comment by alexander-schranz** [comment]
Hello @AliasIO,
is there any issue in this implementation or do you know why it is still not being tracked at https://wappalyzer.com/applications/sulu ?
The detection seems to work correctly when looking at http://sulu.io/en with the extension.

**Pull request merged**
