### PR TITLE
Add HTTP/2 and distinguish it from SPDY

### PR DESCRIPTION
**Pull request by rugk**
Just two questions:
* I've now just copied the icon from SPDY as I could not find any one of HTTP/2. If you have an icon or other ideas about this, let me know.
* Obviously I also could not use `/` in a filename, so I had to left it out. I hope it works too. (although I'm not very confident...)
Are there other ways to define a filename for the picture manually or work around this?

I also compressed the penguin PNG (just because it was annoying to see it as a uncommitted change there although I had nothing changes - so I wanted to change at least something useful there).

Fixes https://github.com/AliasIO/Wappalyzer/issues/990

### CODE REVIEW

**Comment by rugk** [comment]
Okay the first part of my second question has been answered:
`Missing file: src/icons/HTTP/2.png`

**Comment by DaAwesomeP** [comment]
@rugk you can add another commit to fix it. It's not a good idea to put a slash in a filename (in fact, you can't on any filesystem that I've heard of), so you might have to just call it "HTTP2" instead of "HTTP/2" as a workaround.

@AliasIO maybe in the future an optional JSON attribute could allow for an alternative image path or maybe a pattern in the name such as "HTTP/\\/2" could link to the image "HTTP2.png" but still show the name "HTTP/2."

**Comment by AliasIO** [comment]
Technically you could create a subfolder called `HTTP`, with a file called `2.png` in it. :)

I think `HTTP2` is fine though.

**Comment by rugk** [comment]
So currently I can't really encode the slash or do something else?

The issue is just that `HTTP/2` is the official name and I don't really like to use another name. So for now I'm using the "folder workaround". Possibly a fix of this could be implemented later. (https://github.com/AliasIO/Wappalyzer/issues/1004)

**Comment by AliasIO** [comment]
I wasn't really serious about the subfolder hack, I don't think to will work on the website. :)

I'm also not sure about including HTTP/2 as it's a protocol, whereas SPDY arguably is more of a feature.

**Comment by rugk** [comment]
> I'm also not sure about including HTTP/2 as it's a protocol, whereas SPDY arguably is more of a feature.

What? HTTP/2 is just the successor of SPDY. Strictly said no SPDY or HTTP/2 are features, but protocols - *both*.
If you want bto name a feature they could both called "*Faster network transport technology" or something similar stupid.

So open this PR again and let's come back to the file name issue: What do you suggest? Naming it "HTTP2"?

**Comment by rugk** [comment]
Also want to add that the OS, the programming language aren't features too. So "it's no feature" is no argument at all.

**Comment by AliasIO** [comment]
I'd say HTTP/2 is the successor to HTTP 1.1, where SPDY was a notable stopgap. We don't obviously don't report on HTTP 1.1 which I why I said I'm not sure about including HTTP/2. However, since HTTP/2 is still a novelty at this point I don't mind reporting it.

Let's call it 'HTTP2' or 'HTTP 2'.

**Comment by DaAwesomeP** [comment]
The icon file name issue should be resolved with #1012.

**Comment by rugk** [comment]
So can this be merged?

**Comment by AliasIO** [comment]
Sorry for leaving this for so long, are you able to rebase so I can merge this in?

**Comment by rugk** [comment]
This Penguin.png is always appearing as an uncommitted change no matter whether I discard them.
This defectively prevents me from rebasing right now...

**Comment by q--** [comment]
I removed a lowercase version of Penguin.png in #1023. I'm not entirely sure how I fixed things, but you could try something like the following:

0. Checkout your branch _patch-http2_.
1. Make a copy of *Penguin.png*  elsewhere.
1. `git rm` both the lowercase and uppercase _Penguin.png_.
2. `git commit -m Msg`
3. Move the copy of *Penguin.png* back. Make sure the name starts with an uppercase _P_!
7. `git add` _Penguin.png_
9. `git commit --amend`
4. Checkout your _master_ branch.
5. `git pull origin master`
0. Checkout your branch _patch-http2_.
0. `git rebase master`
0. If everything worked out, you can now `git push -f origin patch-http2`.

This assumes you have no uncommitted changes for indexed files. If you do, run `git stash save` before step 3 and `git stash pop` after rebasing.

Create a copy of your git folder first in case something goes wrong!

Also, please note that this works only because I removed `penguin.png` (with a lowercase _p_) in an earlier commit.

**Comment by rugk** [comment]
Thanks for your instructions.
I tried to follow them and until step 11 everythig went well...

There git told me:
```
Using index info to reconstruct a base tree...
A       src/icons/penguin.png
Falling back to patching base and 3-way merge...
error: refusing to lose untracked file at 'src/icons/penguin.png'
CONFLICT (modify/delete): src/icons/penguin.png deleted in f122b13a993a499b52b9d84990c12da6775dca68 and modified in Add HTTP/2 and distinguish it from SPDY. Version Add HTTP/2 and distinguish it from SPDY of src/icons/penguin.png left in tree.
Failed to merge in the changes.
```

Basically I now just created a new PR...

**Pull request closed without merging**
