### PR TITLE
Added Jet e-Business e-Commerce system.

### PR DESCRIPTION
**Pull request by bloodf**
Added Jet e-Business e-Commerce system.

- JET Enterprise
- NEO - Omnichannel Commerce Platform

### CODE REVIEW

**Comment by jvoisin** [comment]
Can you give addresses of websites using those products so people can review your commits to see if they are working, and if there are ways to improve them?

Thanks ♥

**Comment by AlexByte** [comment]
❤

**Comment by bloodf** [comment]
Guys, sorry for the absence of links.

The Infrastructure Team are replicating the DEV Servers response to the production.

Here are the links for the DEV Server.

- NEO Omnichannel Commerce Platform -> https://lefil-hmg-neo1.jet.com.br/

- JET Enterprise -> https://hmg223.jet.com.br/

They provide the systems for a bunch of stores.

Jet Enterprise
http://www.vans.com.br/Default.asp
http://www.sergiok.com.br/
http://www.e-cadeiras.com.br/
https://www.zema.com/

NEO Omnichannel Commerce Platform
It's on clinet validation steps, and it's a brand new product.
The stores will be online by Oct, 1

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
