### PR TITLE
Fix false positive in Twitter Bootstrap

### PR DESCRIPTION
**Pull request by carlos-duran**
Many frameworks use that pattern for their grid system.

https://github.com/AliasIO/Wappalyzer/issues/1589

### CODE REVIEW

**Comment by jvoisin** [comment]
Maybe we could use something else, like ` class="form-control"`, `class="glyphicon glyphicon-` or `class="sr-only`?

**Comment by carlos-duran** [comment]
I agree. Glyphicons are usually used with Bootstrap.
However "form-control" is very common between CSS frameworks. Thanks.

**Comment by AliasIO** [comment]
Thanks!

**Comment by AlexByte** [comment]
Why not to set confidence percentage instead of deletion?

**Comment by jvoisin** [comment]
Because we now have a 100% reliable way of detecting it, without losing much detection ratio.

**Comment by AlexByte** [comment]
Bootstrap isn't detecting on [this](http://wireframesketcher.com/download.html) page. `btn-(default|success|..)` should be added. What about `form-group`?

**Comment by AlexByte** [comment]
Glyphicon is probably a reliable thing, but it is rarely used.

**Pull request merged**
