### PR TITLE
Fix LaunchDarkly xhr definition

### PR DESCRIPTION
**Pull request by myfluxi**
* Uses array instead of string (as per definition)
* Breaks strict type checking

### CODE REVIEW

**Comment by AliasIO** [comment]
What error did you get? All patterns can be either a string or array.

**Comment by myfluxi** [comment]
See: https://github.com/AliasIO/wappalyzer/blob/master/README.md?plain=1#L390

Good news is, all other json values of all definitions are spot on (as per definition).

**Comment by AliasIO** [comment]
Ah, good catch. I've updated the README. Also see the JSON schema:

https://github.com/AliasIO/wappalyzer/blob/master/schema.json

**Comment by myfluxi** [comment]
Addressed in: https://github.com/AliasIO/wappalyzer/commit/21cef7d268a0a92efc2aa298480bdde29ac9ce65
and: https://github.com/AliasIO/wappalyzer/blob/master/schema.json

Thanks 👌🏼

**Pull request closed without merging**
